// PixyDust Terms of Service — counsel-supplied text, reproduced VERBATIM.
// Do not paraphrase, summarise, re-order, or "tidy" any wording here: this is a
// binding legal document and the numbering is cross-referenced internally
// (e.g. Section 20, Section 12.5). Only the counsel-approved source may change it.
import type { LegalDoc } from "./legal";

export const TERMS: LegalDoc = {
  current: "terms",
  kicker: "Legal · governing your use of PixyDust",
  title: "PixyDust Terms of Service",
  subtitle: "These Terms of Service govern your access to and use of PixyDust.",
  lastUpdated: "September 17, 2026",
  numbered: true,
  sections: [
    {
      id: "relationship",
      title: "1. Our Relationship",
      body: [
        "These Terms of Service (“Terms”) govern your access to and use of PixyDust, including our websites, applications, software, features, AI models and tools, augmented reality features, content, and related services (collectively, the “Applications”). These Terms constitute a legally binding agreement between you and PixyDust, LLC (“PixyDust,” “we,” “us,” or “our”).",
        "By accessing or using the Applications, creating an account, purchasing or using Credits, or otherwise indicating your acceptance of these Terms, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Applications.",
        "Our Privacy Policy describes how we collect, use, disclose, and otherwise process personal information in connection with the Applications. The Privacy Policy is a notice and is not part of these Terms.",
        "ARBITRATION AND CLASS ACTION/JURY TRIAL WAIVER NOTICE: THESE TERMS CONTAIN A BINDING ARBITRATION AGREEMENT IN SECTION 20. EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN SECTION 20, YOU AND PixyDust AGREE TO RESOLVE DISPUTES THROUGH BINDING INDIVIDUAL ARBITRATION RATHER THAN IN COURT. YOU ALSO WAIVE THE RIGHT TO A JURY TRIAL AND THE RIGHT TO PARTICIPATE IN A CLASS, COLLECTIVE, CONSOLIDATED, OR REPRESENTATIVE ACTION OR ARBITRATION. PLEASE READ SECTION 20 CAREFULLY.",
      ],
    },
    {
      id: "changes",
      title: "2. Changes to the Applications or Terms",
      body: [
        { h: "2.1 Changes to the Applications" },
        "We may modify, update, add, remove, suspend, discontinue, or otherwise change any part of the Applications, including any features, functionality, AI models, model versions, integrations, tools, content, availability, usage limits, or pricing applicable to future purchases or uses, at any time, with or without notice, subject to applicable law. We do not guarantee that any particular feature, AI model, model version, integration, tool, or functionality will remain available.",
        "PixyDust may establish or modify usage, capacity, rate, concurrency, storage, processing, or similar limits applicable to the Applications or particular features, plans, models, accounts, or functionality and may use measures such as rate limiting, throttling, queuing, rejection of requests, or temporary restrictions to enforce those limits, subject to applicable law.",
        { h: "2.2 Changes to These Terms" },
        "We may update or modify these Terms from time to time, including to reflect changes to the Applications, the way we operate or provide them, our business practices, or applicable legal, regulatory, security, or operational requirements. When we make material changes, we will provide reasonable advance notice where required by applicable law or otherwise appropriate, such as through the Applications, by email, or by other reasonable means.",
        "The updated Terms will become effective on the date specified in the updated Terms or accompanying notice. Your continued use of the Applications after the updated Terms become effective constitutes your acceptance of the updated Terms, except where applicable law requires additional notice or affirmative consent.",
        "PixyDust may require you to affirmatively accept updated Terms before continuing to access or use some or all of the Applications. If you do not provide any required acceptance, PixyDust may restrict or suspend your access to some or all of the Applications until you do so, subject to applicable law.",
      ],
    },
    {
      id: "your-rights",
      title: "3. Your Rights & Use of Our Applications",
      body: [
        "Our Applications let you create, generate, upload, record, edit, process, view, publish, and share content, including through artificial intelligence, augmented reality, and other tools and features that we may make available from time to time.",
        "Subject to your compliance with these Terms, PixyDust grants you a limited, non-assignable, non-exclusive, revocable, and non-sublicensable right to access and use the Applications according to these Terms. PixyDust reserves all rights not expressly granted to you.",
        "By accessing or using our Applications, you represent, warrant, and agree that:",
        {
          clauses: [
            "(a) You have the legal capacity and authority to enter into a legally binding contract with PixyDust.",
            "(b) You are at least eighteen (18) years old and have reached the age of legal majority in your jurisdiction, if the age of legal majority in your jurisdiction is higher than eighteen (18). The Applications are not intended for or available to minors.",
            "(c) You are not a convicted sex offender.",
            "(d) You will abide by these Terms and all applicable local, state, national, and international laws, rules, and regulations.",
            "(e) You are not prohibited from accessing or using the Applications under the laws of the United States or any other applicable jurisdiction, including applicable trade sanctions and export control laws, and you are not subject to sanctions or other restrictions that would prohibit PixyDust from providing the Applications to you.",
            "(f) You will only upload, submit, record, generate, publish, share, or otherwise use content through the Applications if you have all rights, licenses, permissions, releases, and consents necessary to do so, including any rights relating to intellectual property, privacy, publicity, name, image, likeness, voice, recording, or other applicable rights.",
            "(g) You will not use the Applications in a manner that is unlawful, fraudulent, deceptive, harmful, abusive, harassing, infringing, or that violates the rights of any person or entity.",
            "(h) You will use any augmented reality, recording, camera, location-based, or similar features responsibly and safely, remain aware of your surroundings, and comply with applicable laws while using such features.",
            "(i) You are responsible for maintaining the security and confidentiality of your account and credentials and, to the extent permitted by applicable law, for activity conducted through your account.",
            "(j) PixyDust has not previously suspended or terminated your account for violations of these Terms, unless PixyDust has expressly authorized you to create or use another account.",
          ],
        },
        "If we learn or reasonably believe that you do not satisfy any of the eligibility requirements, representations, warranties, or obligations set forth above, we may suspend, restrict, or terminate your account or access to the Applications and take other appropriate measures, subject to these Terms and applicable law.",
        "If you are using the Applications on behalf of a business, organization, or other legal entity:",
        {
          clauses: [
            "(i) “you” and “your” encompass both you as an individual and that entity;",
            "(ii) you represent and warrant that you are an authorized representative of the entity with the authority to legally bind the entity to these Terms, and you agree to these Terms on behalf of the entity; and",
            "(iii) the entity is legally and financially responsible for your access to and use of the Applications and for access to and use of the Applications by its employees, agents, contractors, and other persons acting on its behalf or through its account.",
          ],
        },
        "Except as expressly provided in these Terms, these Terms do not establish or grant rights or remedies to any third-party beneficiaries.",
      ],
    },
    {
      id: "accounts",
      title: "4. Accounts and Account Security",
      body: [
        "Certain features of the Applications may require you to create or maintain an account. You agree to provide accurate, current, and complete information in connection with your account and to keep such information reasonably current. To the extent permitted by applicable law, you are responsible for activity occurring through your account, including purchases and use of Credits.",
        "You are responsible for maintaining the confidentiality and security of your login credentials and for taking reasonable steps to prevent unauthorized access to your account.",
        "You may not sell, transfer, license, rent, or otherwise provide your account or account credentials to another person except as expressly authorized by PixyDust. You have no ownership or other property interest in your account or username. PixyDust may reclaim, change, remove, or reassign a username where reasonably necessary, including in connection with third-party rights, impersonation, inactivity, security concerns, or violations of these Terms.",
        "You may not permit any person who does not satisfy the minimum age requirements in Section 3 to access or use the Applications through your account.",
        "You agree to promptly notify PixyDust at support@pixydust.com if you know or reasonably suspect that your account or credentials have been compromised or used without authorization.",
        "We may require you to verify information associated with your account, reset credentials, or take other security measures where we reasonably believe doing so is necessary to protect you, PixyDust, other users, or the Applications.",
        "If the Applications allow multiple users to access a shared organization, team, or workspace (“Workspace”), the owner or administrator of the Workspace may have authority to access, manage, monitor, share, remove, restrict, or reassign content, users, permissions, settings, and other information associated with that Workspace. Members of a Workspace should not expect their activity or content within the Workspace to be private from the Workspace owner or administrators. The Workspace owner or applicable organization is responsible for the administration of the Workspace and the activities of persons it authorizes to access it.",
        "The Workspace owner or applicable organization is responsible for payment of all applicable fees and charges associated with the Workspace and its members. Rights to access or use a Workspace, including any associated Credits, benefits, or permissions, may not be transferred or reassigned except through functionality made available or expressly authorized by PixyDust.",
      ],
    },
    {
      id: "user-content",
      title: "5. Applications & User Content",
      body: [
        { h: "5.1 User Content" },
        "The Applications may allow you to create, upload, submit, record, capture, generate, process, publish, transmit, or share content (“User Content”). User Content includes:",
        {
          clauses: [
            "(a) photos, video, audio, recordings, and other content captured through the Applications (“Captured Content”);",
            "(b) prompts, instructions, text, images, audio, video, files, data, reference materials, and other content you submit to AI-powered features (“Inputs”);",
            "(c) images, video, audio, text, and other content generated or returned through AI-powered features in response to Inputs (“Outputs”); and",
            "(d) User Content you choose to publish, share, or otherwise make available to other users or the public, whether through the Applications or on any third-party platform, website, service, or other medium (“Public Content”).",
          ],
        },
        { h: "5.2 Ownership of Your Content and License to PixyDust" },
        "As between you and PixyDust, you retain your ownership rights in User Content that you own, subject to the licenses and rights granted in these Terms.",
        "When you create, upload, submit, record, capture, generate, process, publish, transmit, or share User Content through the Applications, you grant PixyDust certain rights and licenses to use that User Content as described in Section 6.",
        "As between you and PixyDust, PixyDust does not claim ownership of your Inputs or Outputs. To the extent permitted by applicable law, and subject to any rights of PixyDust or third parties in underlying materials, models, technology, or content, you may use Outputs generated for you for lawful purposes, including commercial purposes. Subject to these Terms and applicable law, you may transfer or sublicense those rights to clients or other third parties. Your rights in Outputs generated for you will not terminate solely because you cancel a subscription, delete your account, or otherwise stop using the Applications, to the extent you have such rights under applicable law.",
        "Nothing in these Terms represents or guarantees that any Output is eligible for copyright, trademark, patent, or other intellectual property protection.",
        { h: "5.3 Responsibility for User Content; Rights, Permissions and Safety" },
        "You are solely responsible for User Content that you create, capture, submit, upload, record, generate, publish, share, distribute, or otherwise use through or in connection with the Applications.",
        "You represent and warrant that you own or otherwise have obtained all rights, licenses, permissions, releases, and consents necessary for you to provide User Content to the Applications and to grant PixyDust the rights and licenses granted under these Terms.",
        "Without limiting the foregoing, if User Content includes or depicts any person's name, image, likeness, voice, performance, persona, or other identifiable attributes, or includes recordings of or biometric information relating to any person, you represent and warrant that you have obtained all rights, licenses, permissions, releases, and consents necessary to provide such User Content to the Applications and to permit the uses authorized by these Terms, including, where applicable, commercial, advertising, promotional, and marketing uses, without PixyDust being required to obtain additional permission from or pay compensation to that person or any other third party.",
        "If User Content contains music or other audio content, you represent and warrant that you have obtained all rights, licenses, permissions, and clearances necessary for the uses authorized by these Terms, including, where applicable, rights relating to musical compositions, sound recordings, synchronization, reproduction, distribution, public performance, and communication to the public.",
        "You further represent and warrant that PixyDust's exercise of the rights and licenses granted by you under these Terms will not infringe, misappropriate, or otherwise violate any third party's copyright, trademark, patent, rights of publicity, privacy, or personality, contractual rights, or other intellectual property, proprietary, or personal rights.",
        "You must never endanger yourself or others in the pursuit of capturing, creating, recording, generating, or sharing User Content through the Applications.",
        "Additional requirements applicable to augmented reality, recording, camera, location-based, and social features are described in Section 9.",
        { h: "5.4 Compliance and Retention" },
        "By using the Applications, you agree to comply with these Terms. If you violate or we reasonably suspect that you have violated these Terms, we may retain User Content and data or other information relating to the actual or suspected violation and may disclose relevant retained information to third parties, subject to applicable law.",
        "Additional provisions regarding monitoring, moderation, reporting, retention, and disclosure are set forth in Section 13.",
        { h: "5.5 Storage and Availability" },
        "Your User Content may become unavailable for any number of reasons, including operational or technical failures. We do not guarantee that User Content will always remain available. You should maintain separate copies of User Content that is important to you. We may review, restrict, remove, or delete User Content from the Applications at any time, subject to applicable law and these Terms. We generally cannot remove copies of User Content that you or others have shared, downloaded, copied, transmitted, or stored outside the Applications.",
        { h: "5.6 Similar or Identical Outputs" },
        "Because of the nature of generative artificial intelligence, Outputs may not be unique. Other users may receive Outputs that are identical or similar to Outputs generated for you.",
        "You acknowledge and agree that similarity between Outputs does not, by itself, give you any rights or claims against PixyDust or another user.",
      ],
    },
    {
      id: "rights-you-grant",
      title: "6. Rights You Grant Us",
      body: [
        { h: "6.1 User Content" },
        "For User Content that you create, record, capture, upload, submit, generate, process, or otherwise provide through the Applications, you grant PixyDust and our affiliates a non-exclusive, royalty-free, irrevocable, perpetual, sublicensable license throughout the universe to host, store, cache, reproduce, process, analyze, transmit, modify, adapt, and otherwise use such User Content as reasonably necessary to operate, provide, secure, maintain, support, troubleshoot, develop, and improve the Applications and other products and services of PixyDust and its affiliates.",
        "PixyDust may use User Content to develop, train, test, evaluate, enhance, improve, and otherwise support the Applications, artificial intelligence and machine-learning models, algorithms, technologies, products, and services of PixyDust and its affiliates, subject to applicable law and our Privacy Policy. You will not be entitled to compensation for PixyDust's or our affiliates' exercise of the rights and licenses granted with respect to User Content under this Section.",
        "Deletion or removal of User Content, or deletion or termination of your account, will not terminate or revoke the rights and licenses granted to PixyDust and our affiliates under this Section or require PixyDust or our affiliates to delete or cease using User Content, including copies retained in our systems, to the extent permitted by applicable law. PixyDust and our affiliates may continue to exercise the rights and licenses granted under this Section with respect to such User Content after its deletion or removal or the deletion or termination of your account.",
        "Deletion or removal of User Content also will not require PixyDust or our affiliates to reverse, retrain, modify, or otherwise alter any artificial intelligence or machine-learning model, algorithm, technology, product, or service that was developed, trained, tested, evaluated, enhanced, or improved using such User Content, to the extent permitted by applicable law.",
        "If User Content constitutes Public Content, the additional rights and licenses set forth in Section 6.3 will apply.",
        { h: "6.2 Inputs and Outputs" },
        "In addition to the rights granted under Section 6.1, where you use artificial intelligence or machine-learning functionality made available through the Applications, you authorize PixyDust, our affiliates, our service providers, and Third-Party Providers to receive, host, store, reproduce, transmit, process, analyze, modify as technically necessary, and otherwise use your Inputs, Outputs, and related User Content as reasonably necessary to process your requests, generate and deliver Outputs, provide the AI functionality you request, operate and support such functionality, enforce applicable usage requirements, prevent fraud, abuse, and misuse, and maintain the safety, security, and integrity of the Applications. Your use of third-party models, technologies, or services through the Applications may also involve processing of Inputs, Outputs, or related User Content by Third-Party Providers, subject to Section 11 and our Privacy Policy.",
        "Nothing in this Section limits the operational, development, training, testing, evaluation, enhancement, or improvement rights granted to PixyDust under Section 6.1.",
        { h: "6.3 Public Content" },
        "If you intentionally publish, post, share, submit to a public gallery, community, showcase, contest, campaign, promotional program, or otherwise make User Content publicly available such that it constitutes Public Content, you grant PixyDust, our affiliates, and our business partners an unrestricted, non-exclusive, royalty-free, irrevocable, perpetual, sublicensable, and transferable right and license throughout the universe to host, store, cache, analyze, transmit, use, publish, display, reproduce, modify, adapt, edit, translate, create derivative works from, distribute, monetize, promote, exhibit, broadcast, syndicate, synchronize, overlay graphics and auditory effects on, publicly perform, publicly display, communicate, make available, and otherwise use and exploit all or any part of such Public Content, and to authorize others to exercise any of the foregoing rights with respect to such Public Content, in any form and in any media format or distribution method currently known or later developed, for commercial and non-commercial purposes, including to operate, develop, provide, promote, market, and improve the Applications and to develop new products and services.",
        "By making User Content publicly available through the Applications, you also grant other users of the Applications a non-exclusive, royalty-free license throughout the universe to access, view, use, reproduce, download, share, modify, adapt, remix, regenerate from, and create derivative works from such Public Content through or in connection with the functionality made available by the Applications, subject to these Terms and applicable law.",
        "The rights granted to other users under this Section are limited to uses authorized by these Terms and the functionality made available by the Applications and do not grant any independent rights in underlying third-party content or materials.",
        "The license granted to PixyDust, our affiliates, and our business partners under this Section applies to Public Content as a whole and, without limitation, to the separate video, images, sound recordings, musical compositions, and other elements contained in Public Content. The license also includes the right to use any name, username, profile information, image, likeness, and voice included in, depicted in, or intentionally made publicly available in connection with such Public Content to identify, attribute, display, promote, market, monetize, or feature the Public Content, the Applications, PixyDust, and its products and services. PixyDust has no obligation to attribute Public Content to you or any other person unless required by applicable law. You will not be entitled to compensation for PixyDust's, our affiliates', or our business partners' use of Public Content as authorized by this Section.",
        "The rights and licenses granted to PixyDust, our affiliates, and our business partners under this Section are irrevocable and perpetual and will survive the deletion or removal of Public Content, to the extent permitted by applicable law. Deletion or removal of Public Content will not terminate or revoke any rights or licenses granted with respect to such Public Content or prevent the continued exercise of those rights and licenses, including where the Public Content has been accessed, viewed, reproduced, downloaded, shared, copied, distributed, modified, adapted, remixed, regenerated from, incorporated into derivative works, or otherwise used by other users, subject to these Terms and applicable law. To the extent permitted by applicable law, any authorized copy, modification, adaptation, remix, regeneration, derivative work, or other content created or made available through the exercise of those rights may continue to be used, made available, shared, modified, adapted, remixed, regenerated from, and incorporated into further derivative works in accordance with these Terms and the functionality made available by the Applications, notwithstanding the subsequent deletion or removal of the original Public Content.",
        "Deletion or removal also will not require PixyDust to remove copies retained in routine backups or where continued retention is required or permitted by applicable law.",
        { h: "6.4 Moral Rights" },
        "To the extent permitted by applicable law, you irrevocably waive, and agree not to assert against PixyDust, its affiliates, or any other person or entity authorized to exercise rights granted under these Terms, any moral rights or equivalent rights you may have in User Content to the extent necessary for PixyDust or such person or entity to exercise the rights and licenses granted under these Terms.",
        { h: "6.5 Feedback" },
        "We value feedback and suggestions from users. If you provide ideas, feedback, recommendations, or suggestions regarding the Applications, PixyDust may use them without compensation, restriction, or obligation to you. You agree that PixyDust may own and use products, services, features, improvements, or other materials developed based upon or incorporating such feedback, subject to applicable law.",
      ],
    },
    {
      id: "ip",
      title: "7. PixyDust and Application Intellectual Property",
      body: [
        "The content, software, images, text, graphics, illustrations, logos, icons, photographs, audio, videos, music, branding, works of authorship, features, models, technology, overall visual and functional design of the Applications, and other proprietary materials and technology owned by or licensed to PixyDust, our affiliates, licensors, or service providers (collectively, “Application Content”), and all patents, trademarks, service marks, copyrights, and other intellectual property rights relating to the Applications or Application Content, are owned by or licensed to PixyDust, our affiliates, licensors, or service providers, as applicable, and are protected by applicable intellectual property laws.",
        "Except for the limited rights expressly granted under these Terms, you receive no right, title, or interest in or to the Applications or Application Content. The use of Application Content for any purpose not expressly authorized by these Terms is prohibited. Application Content may not be used, downloaded, copied, reproduced, modified, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited except as expressly permitted by these Terms or with the prior written consent of PixyDust or the applicable rights holder.",
        "PixyDust and the applicable rights holders reserve all rights not expressly granted.",
      ],
    },
    {
      id: "acceptable-use",
      title: "8. Acceptable Use and Prohibited Conduct",
      body: [
        "You may not, and may not attempt to, assist, encourage, or enable another person to:",
        {
          clauses: [
            "(a) duplicate, reverse engineer, modify, decompile, decode, disassemble, or create derivative works from the Applications, or derive, attempt to derive, or extract source code, models, algorithms, model weights, underlying components, or other non-public technology of the Applications, except where applicable law expressly prohibits this restriction;",
            "(b) circumvent, disable, evade, interfere with, or defeat security, safety, moderation, authentication, rate-limit, payment, Credit, access-control, watermarking, provenance, or content-authenticity mechanisms;",
            "(c) probe, scan, or test vulnerabilities of the Applications, systems, or networks without PixyDust's prior written authorization;",
            "(d) use the Applications in violation of applicable law or regulation;",
            "(e) infringe or misappropriate intellectual property, privacy, publicity, personality, confidentiality, contractual, or other rights;",
            "(f) create, upload, distribute, solicit, or facilitate child sexual abuse material, sexual exploitation of minors, grooming, or other unlawful sexual content involving minors;",
            "(g) create or distribute non-consensual intimate imagery or sexually explicit material depicting an identifiable person without legally sufficient authorization;",
            "(h) threaten, stalk, harass, bully, abuse, exploit, or endanger another person;",
            "(i) deceptively impersonate another person or create content intended to mislead others about a person's identity, statements, conduct, or endorsement in violation of applicable law;",
            "(j) commit or facilitate fraud, phishing, scams, identity theft, or other deceptive practices;",
            "(k) introduce malware, malicious code, viruses, or other harmful technology;",
            "(l) access, scrape, collect, or extract data from the Applications by automated means except as expressly authorized by PixyDust;",
            "(m) manipulate, counterfeit, duplicate, exploit, or circumvent Credits, billing systems, usage limitations, promotions, or technical restrictions;",
            "(n) use Outputs or access to the Applications to develop, train, fine-tune, distill, benchmark for competitive replication, or otherwise create or improve a competing artificial intelligence model or service, except with PixyDust's prior written permission;",
            "(o) use the Applications to violate applicable export controls, sanctions, or other trade restrictions;",
            "(p) use the Applications in a manner that could damage, disable, overburden, disrupt, or materially impair the Applications or interfere with another user's use;",
            "(q) access or use the Applications other than as permitted by these Terms; or",
            "(r) encourage, direct, or assist anyone else to engage in prohibited conduct.",
          ],
        },
        "You may not submit passwords, authentication credentials, government-issued identification numbers, financial account credentials, or other highly sensitive information through the Applications except where expressly requested or supported by a specific feature of the Applications.",
        "You may not use the Applications to uniquely identify, verify, or authenticate an individual through biometric identifiers or biometric templates, or submit fingerprints, retinal or iris scans, precomputed faceprints, voiceprints, or similar biometric identifiers, except where expressly authorized by PixyDust and permitted by applicable law. This restriction does not prohibit the submission of photographs, video, audio, or other media containing a person's face, likeness, or voice for functionality designed to process such media, provided that you have all rights, permissions, releases, and consents required under these Terms and applicable law.",
        "PixyDust may establish additional acceptable-use, safety, model-specific, or community guidelines from time to time.",
      ],
    },
    {
      id: "ar-recording",
      title: "9. Augmented Reality, Recording and Social Features",
      body: [
        { h: "9.1 Recording and Capturing Content" },
        "Certain Applications may allow you to photograph, film, record, capture, publish, or share people, places, audio, video, or other content. You are responsible for complying with applicable recording, privacy, surveillance, publicity, property, and other laws and for obtaining any permissions or consents required before recording, capturing, publishing, or sharing such content.",
        { h: "9.2 Safety and Surroundings" },
        "Never endanger yourself or others in pursuit of capturing content or using the Applications.",
        "When using augmented reality, camera, recording, location-based, or similar functionality, you are responsible for remaining aware of your surroundings and using the Applications safely.",
        "Do not use the Applications in a manner that distracts you while driving, operating machinery, or engaging in another activity requiring your attention. You are responsible for complying with applicable laws, property restrictions, and safety requirements and for avoiding trespass or entry into unsafe or restricted areas.",
        { h: "9.3 Social and Community Features" },
        "The Applications may allow users to maintain profiles, publish User Content, communicate with others, comment, follow users, collaborate, or otherwise participate in social or community features. You are responsible for your interactions with other users. PixyDust does not guarantee the identity, conduct, statements, accuracy, or intentions of other users and is not responsible for interactions between users except to the extent required by applicable law. We may moderate, restrict, remove, or disable access to User Content or social functionality in accordance with these Terms.",
      ],
    },
    {
      id: "ai-features",
      title: "10. Artificial Intelligence Features and Outputs",
      body: [
        { h: "10.1 Generative AI" },
        "Certain Applications use artificial intelligence and machine-learning technologies to generate or transform images, videos, audio, text, and other content based upon Inputs. You acknowledge that artificial intelligence and machine-learning technologies are probabilistic and evolving and may produce unexpected results.",
        { h: "10.2 No Guarantee Regarding Outputs" },
        "PixyDust does not represent or warrant that Outputs will be accurate, complete, reliable, factual, error-free, appropriate, original, unique, non-infringing, or suitable for any particular purpose.",
        "Outputs may contain errors, inaccuracies, artifacts, offensive material, or content resembling material created for or by other users or third parties.",
        { h: "10.3 Review Before Use" },
        "You are responsible for evaluating Outputs before using, publishing, distributing, relying upon, or commercially exploiting them. You should not rely upon Outputs as the sole source of truth or as a substitute for professional judgment where accuracy is important.",
        { h: "10.4 Professional and High-Impact Decisions" },
        "Outputs are not intended to constitute medical, legal, financial, investment, accounting, or other professional advice. In addition, you may not use the Applications to make or materially assist in making decisions concerning another person's eligibility for, access to, or receipt of employment, housing, credit, insurance, education, government benefits or services, or other high-impact opportunities or services, where such use is prohibited or restricted by applicable law.",
        { h: "10.5 Intellectual Property and Outputs" },
        "PixyDust does not guarantee that an Output is eligible for intellectual property protection or that your use of an Output will not infringe, misappropriate, or otherwise violate third-party rights.",
        "PixyDust does not review, verify, or perform intellectual property, rights-clearance, or other legal clearance searches with respect to Inputs or Outputs. You are responsible for determining whether your intended use of an Output is lawful and for obtaining any rights or permissions necessary for such use.",
        { h: "10.6 AI-Generated Content Disclosures" },
        "When required by applicable law, you must clearly and conspicuously disclose that an Output was generated or manipulated using artificial intelligence or otherwise comply with applicable requirements concerning the identification, labeling, or disclosure of AI-generated or AI-manipulated content.",
        { h: "10.7 Watermarks, Content Credentials and Provenance Information" },
        "PixyDust may apply or embed watermarks, Content Credentials, provenance metadata, digital signatures, fingerprints, or other identifiers or technical measures in or in connection with Outputs to identify, authenticate, trace, or provide information concerning the source, creation, modification, or use of such Outputs. You may not remove, obscure, alter, falsify, circumvent, or interfere with any such watermark, Content Credential, provenance information, digital signature, fingerprint, identifier, or technical measure except as expressly permitted by PixyDust.",
      ],
    },
    {
      id: "third-party",
      title: "11. Third-Party Providers and Services",
      body: [
        { h: "11.1 Third-Party Providers; Third-Party Services" },
        "Certain features of the Applications may use, integrate with, or depend upon third parties (“Third-Party Providers”). Artificial intelligence models, APIs, cloud infrastructure, hosting services, payment processing services, data sources, software, and other products, services, technologies, or functionality supplied or operated by Third-Party Providers are referred to as “Third-Party Services.”",
        { h: "11.2 Third-Party Provider Terms" },
        "Your use of a particular Third-Party Service may be subject to additional restrictions, acceptable-use policies, licenses, or terms imposed by the applicable provider. Where a Third-Party Provider imposes restrictions applicable to your use of a particular Third-Party Service, you agree to comply with those restrictions.",
        { h: "11.3 Third-Party Service Availability" },
        "PixyDust may add, remove, or replace any Third-Party Provider and may add, remove, replace, restrict, suspend, modify, or discontinue access to any Third-Party Service, model, model version, integration, or feature at any time. Purchase or possession of Credits does not guarantee continued access to any particular AI model, model version, Third-Party Provider, Third-Party Service, feature, generation method, speed, resolution, capability, or functionality.",
        { h: "11.4 Third-Party Changes and Outages" },
        "Third-Party Services may experience outages, delays, capacity constraints, policy changes, technical failures, model changes, price changes, discontinuation, or other changes or disruptions. PixyDust does not guarantee the continued availability, performance, latency, throughput, accuracy, or quality of any Third-Party Service.",
        { h: "11.5 Third-Party Offerings" },
        "The Applications may display, include, link to, integrate with, provide access to, or otherwise make available websites, applications, accounts, advertisements, promotions, data, information, features, content, products, or services provided, supplied, or operated by third parties (“Third-Party Offerings”). Certain features of the Applications may also use, integrate with, or depend upon Third-Party Services.",
        "If you access, use, interact with, purchase from, or connect your account to any Third-Party Offering or Third-Party Service, your access to and use of that offering or service, and your relationship or dealings with the applicable third party, may be subject to the applicable third party’s terms, policies, licenses, conditions, and practices.",
        "If you connect a third-party account, service, or platform to the Applications, you represent and warrant that you are authorized to connect that account and to provide PixyDust and its service providers with any access, permissions, credentials, tokens, content, or information necessary for the requested integration. You are responsible for the proper setup and authorization of any such connection. PixyDust may access, receive, process, and use content and information made available through the connected account as reasonably necessary to provide the applicable functionality and as otherwise permitted by these Terms and our Privacy Policy. PixyDust does not control, and is not responsible for, the availability, suspension, restriction, termination, functionality, or conduct of any connected third-party account, platform, or provider.",
        "To the maximum extent permitted by applicable law, PixyDust and its affiliates do not control, endorse, evaluate, verify, or guarantee any Third-Party Offering or Third-Party Service. PixyDust and its affiliates disclaim responsibility and liability arising from or relating to any Third-Party Offering or Third-Party Service, including its availability, accuracy, security, or privacy practices, or the products, services, representations, policies, acts, omissions, or conduct of any third party.",
        "Your dealings or interactions with third parties are solely between you and the applicable third party, except to the extent otherwise expressly provided by PixyDust or required by applicable law.",
        { h: "11.6 Advertising and Promotions" },
        "We may display advertisements, promotions, sponsored content, offers, or other commercial content within or in connection with the Applications, including personalized offers, subject to applicable law. Advertisements, promotions, sponsored content, offers, and other commercial content provided, supplied, or operated by third-party advertisers, sponsors, promotional partners, or other third parties constitute Third-Party Offerings and are subject to Section 11.5.",
      ],
    },
    {
      id: "credits",
      title: "12. Credits, Purchases, Pricing and Refunds",
      body: [
        { h: "12.1 Credits" },
        "PixyDust may allow you to purchase Credits separately, obtain Credits as part of a subscription, or receive promotional, complimentary, bonus, trial, or other Credits (collectively, “Credits”). Credits purchased separately or in addition to a subscription are referred to as “Add-On Credits.”",
        "Credits represent a limited contractual right to initiate eligible generation or processing requests and receive the resulting Outputs or other applicable digital content or functionality, in accordance with these Terms. Credits are not legal tender, currency, cryptocurrency, stored value, a bank deposit, security, or other financial instrument. Credits have no cash value, do not accrue interest, and may not be redeemed for cash except where required by applicable law. Credits may not be sold, transferred, assigned, exchanged, or traded except as expressly authorized by PixyDust.",
        "Access to the Applications may be available without charge. Certain generation, processing, or other functionality requires Credits. When you initiate functionality requiring Credits, the applicable number of Credits will be deducted from your account, and PixyDust will process the applicable request and, where applicable, provide the resulting Output. PixyDust's systems and records will determine Credit balances, usage, deductions, and transactions, except in the case of manifest error.",
        { h: "12.2 Credit Costs" },
        "The number of Credits required to use a feature or generate an Output may vary depending upon factors such as the AI model, feature, duration, resolution, quality, settings, computational requirements, or other parameters. PixyDust may change the number of Credits required for future uses of a feature or model. Changes to Credit costs will apply prospectively and will not retroactively deduct additional Credits for completed transactions.",
        { h: "12.3 Pricing and Payment" },
        "You agree to pay all amounts presented to you at the time of purchase, including applicable taxes and fees. Payments may be processed by third-party payment providers and may be subject to their terms. We may correct pricing, billing, or technical errors and may cancel or reverse transactions resulting from obvious errors, fraud, abuse, or unauthorized activity, subject to applicable law. You are responsible for maintaining current, complete, and accurate payment information associated with your account. If we are unable to process a payment when due, we may suspend, downgrade, or terminate the applicable subscription or restrict access to subscription benefits until payment is successfully received, subject to applicable law.",
        { h: "12.4 Subscriptions and Automatic Renewal" },
        "PixyDust may offer subscription plans that provide access to certain features, functionality, Credits, benefits, or usage allowances during a recurring subscription period. The features, Credits, benefits, usage limits, price, and billing period applicable to your subscription will be disclosed at the time of purchase. Unless otherwise disclosed at the time of purchase or prohibited by applicable law, subscriptions automatically renew for successive subscription periods until canceled. By purchasing a subscription, you authorize PixyDust or its payment provider to charge the applicable subscription fees, taxes, and other disclosed charges to your selected payment method at the beginning of each subscription period.",
        "You may cancel your subscription through the cancellation methods made available by PixyDust. Unless otherwise required by applicable law or expressly stated at the time of purchase, cancellation will take effect at the end of your then-current paid subscription period, and you will retain access to the applicable subscription benefits until that time.",
        "Any subscription upgrade will take effect immediately, and any applicable incremental or prorated charges will be disclosed when you make the change. Any subscription downgrade will take effect at the beginning of your next subscription period. Any applicable charges, Credits, benefits, usage limits, prorations, or other adjustments resulting from the change will be determined and disclosed in accordance with the applicable plan terms and the applicable checkout or account interface.",
        "PixyDust may change subscription prices or plan features prospectively upon notice as required by applicable law. Any price change will take effect no earlier than your next applicable renewal period following the effective date of the change, subject to any additional notice or consent required by applicable law.",
        "PixyDust may offer free trials, promotional pricing, or other promotional subscription offers. Any additional terms applicable to an offer will be disclosed when you enroll. A free trial or promotional subscription offer that automatically converts to a paid subscription will renew at the applicable price when the trial or promotional period ends unless you cancel before then.",
        { h: "12.5 Credit Expiration and Rollover" },
        "Promotional, complimentary, bonus, trial, or other non-purchased Credits may expire according to the terms disclosed when they are issued.",
        "Purchased Add-On Credits expire ninety (90) days after they are purchased and issued. Unused Credits provided as part of a subscription expire and do not roll over to subsequent subscription periods, as described in the terms of the applicable subscription plan. Upon cancellation or expiration of a subscription, any unused subscription Credits remaining in your account will expire and be forfeited.",
        { h: "12.6 Generation Failures" },
        "If a generation fails because of a qualifying technical failure attributable to the Applications, PixyDust may, in its discretion or as otherwise required by applicable law, restore the Credits charged for that failed generation. A generation is not necessarily a qualifying technical failure merely because you dislike an Output, an Output does not satisfy your expectations, a prompt is rejected or moderated, a Third-Party Provider refuses to process a request, or an Output differs from results produced by another model or service.",
        { h: "12.7 Refunds" },
        "Except where required by applicable law, subscription fees, purchases of Credits or Add-On Credits, and purchases of other digital products are final and non-refundable. Cancellation of a subscription does not entitle you to a refund or credit for any portion of the then-current subscription period, except where required by applicable law. Nothing in these Terms limits any refund, withdrawal, cancellation, or other consumer right that cannot lawfully be waived.",
        { h: "12.8 Chargebacks and Payment Abuse" },
        "Fraudulent or abusive chargebacks, payment disputes, payment reversals, or attempts to obtain or use Credits without valid payment may result in suspension or termination of your account, cancellation of Credits, or other appropriate action, subject to applicable law.",
      ],
    },
    {
      id: "moderation",
      title: "13. Monitoring, Moderation and Reporting",
      body: [
        "PixyDust may, but is not obligated to, monitor, review, screen, filter, restrict, block, or remove Inputs, Outputs, User Content, accounts, or activity for purposes including operating the Applications, enforcing these Terms, protecting users, preventing fraud or abuse, complying with law, and maintaining safety and security. We may use automated systems, human review, or both to identify potentially prohibited or harmful activity. We may block or refuse to process an Input, prevent or restrict generation of an Output, remove User Content, restrict functionality, or suspend or terminate access where we reasonably believe activity violates these Terms, applicable law, provider requirements, or our safety policies.",
        "If PixyDust notifies you that User Content, an Output, or other material violates these Terms, applicable law, provider requirements, or the rights of another person or entity, you must promptly comply with PixyDust's reasonable instructions concerning that material, including, where directed, ceasing its use or distribution, removing or deleting copies within your possession or control, and refraining from using the Applications to regenerate substantially the same prohibited material.",
        "We may retain User Content and information relating to suspected violations and disclose relevant information to law enforcement, regulators, rights holders, safety organizations, service providers, or other third parties where permitted or required by applicable law, including as reasonably necessary to protect the safety, rights, or property of PixyDust, our users, or others; investigate, prevent, remedy, or enforce potential violations of these Terms; address suspected unlawful activity; or detect, prevent, or resolve fraud, abuse, or security concerns.",
        "Users may report content or conduct through mechanisms we make available or by contacting support@pixydust.com. PixyDust may cooperate with lawful removal requests, intellectual property complaints, safety reports, and requests concerning non-consensual intimate imagery, exploitation, or other unlawful content.",
      ],
    },
    {
      id: "dmca",
      title: "14. Intellectual Property Complaints and DMCA",
      body: [
        "PixyDust respects intellectual property rights and expects users to do the same. If you believe material available through the Applications infringes your copyright, you may submit a notice under the Digital Millennium Copyright Act (“DMCA”) to our designated agent. A valid DMCA notice should include the information required by 17 U.S.C. § 512(c)(3), including:",
        {
          clauses: [
            "(a) identification of the copyrighted work claimed to have been infringed;",
            "(b) identification of the allegedly infringing material and information reasonably sufficient to permit PixyDust to locate it;",
            "(c) your contact information;",
            "(d) a statement that you have a good-faith belief that use of the material is not authorized by the copyright owner, its agent, or law;",
            "(e) a statement, made under penalty of perjury, that the information in your notice is accurate and that you are authorized to act on behalf of the copyright owner; and",
            "(f) your physical or electronic signature.",
          ],
        },
        "DMCA notices should be sent to: dmca@pixydust.com",
        "If your content is removed in response to a DMCA notice, you may have the right to submit a counter-notification as provided by applicable law. PixyDust may terminate, in appropriate circumstances, accounts of users who are repeat infringers. Claims concerning trademarks or other intellectual property may be submitted to ip@pixydust.com.",
      ],
    },
    {
      id: "indemnification",
      title: "15. Indemnification",
      body: [
        "To the fullest extent permitted by applicable law, you agree to defend, indemnify, and hold harmless PixyDust, its parents, subsidiaries, affiliates, business partners, licensors, service providers, Third-Party Providers, underlying technology providers, and their respective officers, directors, employees, workforce, representatives, agents, and consultants from and against claims, demands, actions, liabilities, losses, damages, judgments, settlements, costs, and expenses, including reasonable attorneys' fees and disbursements, arising out of or relating to:",
        {
          clauses: [
            "(a) your breach or alleged breach of these Terms;",
            "(b) your violation of any representation, warranty, covenant, or obligation under these Terms;",
            "(c) your access to or use of the Applications;",
            "(d) your User Content;",
            "(e) your use, publication, distribution, commercialization, or other exploitation of Outputs;",
            "(f) your infringement, misappropriation, or violation of intellectual property, privacy, publicity, personality, confidentiality, contractual, or other rights of another person or entity;",
            "(g) your violation of applicable law; or",
            "(h) your interactions with other users or third parties through or in connection with the Applications.",
          ],
        },
        "PixyDust reserves the right, at your expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and you agree to reasonably cooperate with PixyDust in the defense of such matter. You will be responsible for the reasonable attorneys' fees, costs, and expenses incurred by PixyDust and the other indemnified parties in connection with the defense of any such matter, to the extent subject to your indemnification obligations under this Section.",
        "You may not settle any matter subject to indemnification under this Section without PixyDust's prior written consent if the settlement imposes any liability, obligation, admission, or restriction on PixyDust or any other indemnified party.",
      ],
    },
    {
      id: "warranties",
      title: "16. Disclaimer of Warranties",
      body: [
        "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATIONS ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS.",
        "PixyDust AND ITS AFFILIATES, LICENSORS, SERVICE PROVIDERS, AND BUSINESS PARTNERS DISCLAIM ALL WARRANTIES, REPRESENTATIONS, GUARANTEES, AND CONDITIONS, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, TO THE EXTENT PERMITTED BY LAW.",
        "WITHOUT LIMITING THE FOREGOING, WE DO NOT WARRANT THAT:",
        {
          clauses: [
            "(a) THE APPLICATIONS WILL MEET YOUR SPECIFIC REQUIREMENTS;",
            "(b) YOUR USE OF THE APPLICATIONS WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE;",
            "(c) INFORMATION OR CONTENT OBTAINED THROUGH THE APPLICATIONS WILL BE ACCURATE, COMPLETE, OR RELIABLE;",
            "(d) OUTPUTS WILL BE ACCURATE, FACTUAL, COMPLETE, ORIGINAL, UNIQUE, NON-INFRINGING, LEGAL, APPROPRIATE, OR SUITABLE FOR YOUR INTENDED PURPOSE;",
            "(e) ANY OUTPUT WILL QUALIFY FOR COPYRIGHT, TRADEMARK, PATENT, OR OTHER INTELLECTUAL PROPERTY PROTECTION;",
            "(f) ANY PARTICULAR AI MODEL, MODEL VERSION, PROVIDER, FEATURE, INTEGRATION, OR FUNCTIONALITY WILL REMAIN AVAILABLE;",
            "(g) THIRD-PARTY PROVIDERS OR OTHER THIRD-PARTY SERVICES WILL OPERATE WITHOUT INTERRUPTION, DELAY, ERROR, CAPACITY LIMITATION, OR CHANGE; OR",
            "(h) DEFECTS OR ERRORS WILL BE CORRECTED.",
          ],
        },
        "YOU ACKNOWLEDGE THAT OUTPUTS MAY CONTAIN ERRORS, INACCURACIES, OFFENSIVE CONTENT, OR MATERIAL THAT MAY RESEMBLE THIRD-PARTY CONTENT, AND THAT YOU ARE RESPONSIBLE FOR REVIEWING AND EVALUATING OUTPUTS BEFORE USING THEM.",
      ],
    },
    {
      id: "liability",
      title: "17. Limitation of Liability",
      body: [
        "NOTHING IN THESE TERMS EXCLUDES OR LIMITS LIABILITY THAT CANNOT LAWFULLY BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW, INCLUDING, WHERE APPLICABLE, LIABILITY FOR DEATH OR PERSONAL INJURY CAUSED BY THE NEGLIGENCE OF PixyDust OR ITS EMPLOYEES, AGENTS, OR SUBCONTRACTORS, OR FOR FRAUD OR FRAUDULENT MISREPRESENTATION.",
        "SUBJECT TO THE FOREGOING, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PixyDust AND ITS AFFILIATES, LICENSORS, SERVICE PROVIDERS, BUSINESS PARTNERS, THIRD-PARTY PROVIDERS, UNDERLYING TECHNOLOGY PROVIDERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND REPRESENTATIVES (COLLECTIVELY, THE “PixyDust PARTIES”) WILL NOT BE LIABLE FOR ANY:",
        {
          clauses: [
            "(a) DIRECT OR INDIRECT LOSS OF PROFITS OR REVENUE;",
            "(b) LOSS OF GOODWILL;",
            "(c) LOSS OF BUSINESS OR OPPORTUNITY;",
            "(d) LOSS, CORRUPTION, OR UNAVAILABILITY OF DATA OR CONTENT;",
            "(e) INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES; OR",
            "(f) LOSS OR DAMAGE RESULTING FROM:",
          ],
        },
        {
          clauses: [
            "(i) RELIANCE UPON THE COMPLETENESS, ACCURACY, OR EXISTENCE OF ADVERTISING, OR ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY ADVERTISER OR SPONSOR IN CONNECTION WITH THE APPLICATIONS;",
            "(ii) CHANGES TO THE APPLICATIONS OR PERMANENT OR TEMPORARY CESSATION OF ANY PORTION OF THE APPLICATIONS;",
            "(iii) DELETION, CORRUPTION, LOSS, OR FAILURE TO STORE USER CONTENT, COMMUNICATIONS, OR OTHER DATA MAINTAINED OR TRANSMITTED BY OR THROUGH YOUR USE OF THE APPLICATIONS;",
            "(iv) OUTPUTS OR YOUR RELIANCE UPON, PUBLICATION OF, DISTRIBUTION OF, OR USE OF OUTPUTS;",
            "(v) THE ACTS, OMISSIONS, AVAILABILITY, PERFORMANCE, POLICIES, OR TECHNOLOGY OF THIRD-PARTY PROVIDERS OR OTHER THIRD-PARTY SERVICES;",
            "(vi) THE REMOVAL, REPLACEMENT, MODIFICATION, OR DISCONTINUATION OF ANY AI MODEL, MODEL VERSION, FEATURE, INTEGRATION, OR PROVIDER;",
            "(vii) UNAUTHORIZED ACCESS TO YOUR ACCOUNT RESULTING FROM YOUR FAILURE TO MAINTAIN REASONABLE SECURITY OVER YOUR CREDENTIALS; OR",
            "(viii) DECISIONS MADE BASED UPON INFORMATION OR OUTPUTS PROVIDED THROUGH THE APPLICATIONS.",
          ],
        },
        "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE TOTAL AGGREGATE LIABILITY OF THE PixyDust PARTIES FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE APPLICATIONS OR THESE TERMS WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO PixyDust FOR THE APPLICATIONS DURING THE SIX (6) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM OR (B) ONE HUNDRED U.S. DOLLARS (US $100).",
        "THE LIMITATIONS IN THIS SECTION APPLY REGARDLESS OF THE THEORY OF LIABILITY AND EVEN IF PixyDust OR ANY OTHER PixyDust PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, EXCEPT WHERE SUCH LIMITATION IS PROHIBITED BY APPLICABLE LAW.",
      ],
    },
    {
      id: "termination",
      title: "18. Suspension and Termination",
      body: [
        { h: "18.1 Suspension or Restriction" },
        "PixyDust may suspend, restrict, limit, or disable your access to some or all of the Applications where we reasonably believe:",
        {
          clauses: [
            "(a) you have violated these Terms;",
            "(b) your account has been compromised or used fraudulently;",
            "(c) your activity presents a security, legal, regulatory, financial, or safety risk;",
            "(d) suspension is necessary to comply with applicable law, legal process, or a Third-Party Service requirement; or",
            "(e) suspension is reasonably necessary to protect PixyDust, the Applications, another user, or a third party.",
          ],
        },
        { h: "18.2 Termination by PixyDust" },
        "Subject to applicable law, PixyDust may terminate your account or access to the Applications if you do not meet the eligibility requirements in Section 3, or for material or repeated violations of these Terms, fraud, abuse, unlawful conduct, security risks, or other grounds described in these Terms. Where practicable and appropriate, PixyDust may provide notice or an opportunity to cure before termination, but is not required to do so where immediate action is reasonably necessary.",
        "PixyDust may also discontinue an Application or terminate access without cause upon reasonable notice where appropriate, subject to applicable law and any rights concerning purchased Credits or other prepaid services.",
        { h: "18.3 Termination by You" },
        "You may stop using the Applications at any time and may request deletion of your account using the functionality we provide or by contacting support@pixydust.com, subject to applicable retention requirements.",
        { h: "18.4 Effect of Termination" },
        "Termination does not relieve you of any obligations incurred before termination or affect any rights, licenses, remedies, or provisions that survive termination under these Terms. Except where required by applicable law, voluntary termination, account deletion, or cessation of use of the Applications does not entitle you to a refund for subscription fees, unused Credits, Add-On Credits, or other amounts previously paid.",
        "If you voluntarily delete your account, any unused Credits associated with that account will no longer be available for use and are canceled and forfeited upon deletion, without refund except where required by applicable law.",
        "Where an account is terminated for fraud, abuse, chargeback activity, or material violation of these Terms, unused Credits are canceled and forfeited to the extent permitted by applicable law.",
        "To the maximum extent permitted by applicable law, PixyDust and the other PixyDust Parties will not be liable to you or any third party for any suspension, restriction, termination, or disabling of access to the Applications or your account, or for any resulting loss or unavailability of User Content, Outputs, account functionality, or other data or benefits.",
      ],
    },
    {
      id: "international",
      title: "19. International Users and Consumer Rights",
      body: [
        "The Applications are operated by PixyDust from the United States and may be accessible from other jurisdictions. You are responsible for determining whether your access to and use of the Applications is lawful in your jurisdiction and for complying with applicable local laws. Nothing in these Terms excludes, restricts, or modifies any consumer guarantee, statutory right, remedy, or other protection, including any mandatory cancellation, withdrawal, refund, or warranty right, that applicable law does not permit the parties to exclude, restrict, or modify.",
        { h: "19.1 EEA/UK Right of Withdrawal" },
        "If you are a consumer resident in the European Economic Area or the United Kingdom, you may have the right to withdraw from your purchase of Credits or other paid digital products, without giving any reason, within fourteen (14) days from the date of purchase or, where applicable, the date the applicable contract is entered into, subject to applicable law.",
        "To exercise any applicable right of withdrawal, you must inform PixyDust of your decision before the applicable withdrawal period expires by a clear statement sent to support@pixydust.com. If you validly exercise a right of withdrawal, PixyDust will provide any reimbursement required by applicable law within the time and using the payment method required by applicable law.",
        "Where applicable law provides a withdrawal period, you may request that PixyDust begin supplying digital content or performing services before that period expires. Any such request, consent, or acknowledgment will apply only to the extent permitted by applicable law, and PixyDust will provide any confirmation required by applicable law.",
        "For digital content not supplied on a tangible medium, which may include generated Outputs or other digital content supplied through the Applications, where you have expressly consented to supply beginning during the withdrawal period and acknowledged that you will lose your right of withdrawal once supply begins, you will lose that right once PixyDust begins supplying the applicable digital content, to the extent permitted by applicable law. Use of any portion of Credits obtained as part of a single purchase or Credit allocation will result in the loss of any applicable right of withdrawal with respect to that entire purchase or allocation, including any unused Credits remaining from that purchase or allocation, to the extent permitted by applicable law.",
        "For services, if you expressly request that performance begin during the withdrawal period and subsequently exercise a valid right of withdrawal before performance is complete, you may be required to pay an amount proportionate to the services provided before you informed PixyDust of your decision to withdraw, to the extent permitted by applicable law.",
        "For purposes of this Section, use of Credits to initiate a generation or processing request, or other Credit-based functionality constitutes use of the applicable Credits and may constitute the beginning of performance or supply. Supply of digital content may begin when PixyDust begins providing or making available the applicable generated Output or other digital content. Merely logging into, browsing, or viewing the Applications without using Credits does not, by itself, constitute use of Credits or supply of paid digital content.",
        "Nothing in this Section limits or excludes any mandatory consumer right or remedy available to you under applicable law that cannot lawfully be limited, excluded, or waived.",
      ],
    },
    {
      id: "arbitration",
      title: "20. Arbitration, Class-Action Waiver, and Jury Waiver",
      body: [
        "PLEASE READ THIS SECTION CAREFULLY BECAUSE IT PROVIDES THAT YOU AGREE TO RESOLVE CERTAIN DISPUTES THROUGH BINDING INDIVIDUAL ARBITRATION AND INCLUDES A CLASS ACTION WAIVER AND JURY TRIAL WAIVER.",
        "This Section 20 constitutes the arbitration agreement between you and the PixyDust Parties (the “Arbitration Agreement”). This Arbitration Agreement supersedes prior versions to the extent permitted by applicable law and extends to PixyDust and the PixyDust Parties.",
        { h: "20.1 Applicability of Arbitration Agreement" },
        "You and the PixyDust Parties agree that all claims and disputes, whether based in contract, tort, statute, or otherwise, arising out of or relating to these Terms, use of the Applications, or communications between you and the PixyDust Parties that are not brought in small claims court will be resolved by binding arbitration on an individual basis, except that you and the PixyDust Parties are not required to arbitrate disputes or claims within the jurisdiction of a small claims court consistent with applicable jurisdictional and dollar limits, provided the matter proceeds individually and not as a class action. Notwithstanding the foregoing, the PixyDust Parties may seek temporary, preliminary, or other provisional injunctive or equitable relief from a court of competent jurisdiction where reasonably necessary to protect intellectual property rights or preserve the status quo pending arbitration. The PixyDust Parties' pursuit of such relief will not waive or otherwise affect the obligation to arbitrate the underlying claim or dispute.",
        "To the extent permitted by applicable law, “all claims and disputes” includes claims and disputes that arose between the parties before the applicable version of these Terms became effective. Disputes concerning arbitrability, including the scope, applicability, enforceability, revocability, or validity of this Arbitration Agreement, will be determined by the arbitrator except as expressly provided in this Section.",
        { h: "20.2 Informal Dispute Resolution First" },
        "Before initiating arbitration, the party asserting a dispute must provide an individualized written pre-arbitration demand (“Pre-Arbitration Demand”). A Pre-Arbitration Demand to PixyDust must be sent to: arbitration@pixydust.com",
        "A Pre-Arbitration Demand must relate to and be submitted on behalf of a single individual. A Pre-Arbitration Demand submitted on behalf of multiple individuals will not satisfy this Section with respect to any such individual. The Pre-Arbitration Demand must include the individual's name, applicable username or account information, telephone number, email address, mailing address, a description of the dispute and requested relief, and the individual's signature.",
        "If represented by counsel, applicable counsel contact information should also be included. If the PixyDust Parties have a dispute with you, the PixyDust Parties may send their individualized Pre-Arbitration Demand, including the applicable information required above, to the email address, phone number, or other contact information associated with your account. If the dispute is not resolved within sixty (60) days after a valid Pre-Arbitration Demand is sent, arbitration may then be filed.",
        "Compliance with this informal dispute-resolution procedure is a condition precedent to commencing arbitration to the extent permitted by applicable law. To the extent permitted by applicable law, the arbitrator shall dismiss any arbitration filed without compliance with this informal dispute-resolution procedure. Notwithstanding the foregoing, the requirements of this Section 20.2 do not prevent the PixyDust Parties from seeking temporary, preliminary, or other provisional injunctive or equitable relief as permitted under Section 20.1.",
        { h: "20.3 Arbitration Rules" },
        "The Federal Arbitration Act, including its procedural provisions, governs the interpretation and enforcement of this Arbitration Agreement, and not state arbitration law.",
        "Arbitration will be administered by ADR Services, Inc. (“ADR Services”) under its applicable arbitration rules then in effect. If ADR Services declines or is unable to administer the arbitration, the arbitration will be administered by National Arbitration and Mediation (“NAM”) under its applicable arbitration rules then in effect. The applicable arbitration rules will govern all aspects of the arbitration except to the extent they conflict with these Terms or applicable law. The arbitration will be conducted by one neutral arbitrator.",
        "Any claim or dispute where the total amount sought is less than $10,000 USD may be resolved through binding non-appearance arbitration, at the option of the party seeking relief, subject to applicable law. For claims or disputes where the total amount sought is $10,000 USD or more, the right to a hearing will be determined by the applicable arbitration rules.",
        { h: "20.4 Non-Appearance Arbitration" },
        "If non-appearance arbitration is elected, the arbitration will be conducted by telephone, videoconference, online proceedings, written submissions, or any combination of those methods, and the specific manner will be chosen by the party initiating the arbitration, subject to applicable law. No personal appearance by the parties or witnesses will be required unless mutually agreed by the parties or required by applicable law.",
        { h: "20.5 Fees" },
        "Responsibility for arbitration filing fees, administrative fees, arbitrator compensation, and other arbitration costs will be determined by the applicable arbitration rules and applicable law. If PixyDust initiates arbitration against you, PixyDust will pay arbitration costs to the extent required by the applicable arbitration rules or applicable law. Nothing in this Section requires you to pay fees or costs that applicable law or the applicable arbitration rules prohibit PixyDust from imposing upon you.",
        "To the extent permitted by the applicable arbitration rules or applicable law, PixyDust may seek, and the arbitrator may award, reallocation or reimbursement of arbitration filing fees, administrative fees, arbitrator compensation, and other arbitration costs if a claim or counterclaim is frivolous, is filed for an improper purpose, or otherwise warrants such reallocation or reimbursement.",
        "Except as otherwise provided by applicable law or the applicable arbitration rules, each party will bear its own attorneys’ fees and expenses incurred in arbitration. Notwithstanding the foregoing, the arbitrator may award attorneys’ fees and expenses if a claim, defense, or relief sought is frivolous, is brought for an improper purpose, or otherwise warrants such an award under applicable law or the applicable arbitration rules.",
        "If either party must initiate or participate in a court proceeding to enforce this Arbitration Agreement or concerning satisfaction of any condition precedent to arbitration, the party that substantially prevails may recover its reasonable attorneys’ fees and expenses, to the extent permitted by applicable law.",
        { h: "20.6 Authority of the Arbitrator" },
        "The arbitrator will determine the rights and liabilities of you and the PixyDust Parties and, except where a determination is expressly reserved for a court under this Arbitration Agreement or applicable law, will determine matters within the arbitrator's jurisdiction.",
        "The dispute will not be consolidated with other matters or joined with claims involving other parties except where expressly permitted by this Arbitration Agreement. The arbitrator will have authority to grant motions dispositive of all or part of any claim or dispute and to grant monetary and non-monetary relief available to an individual under applicable law, the applicable arbitration rules, and these Terms.",
        "The arbitrator will issue a written award consistent with the applicable arbitration rules, including the essential findings and conclusions upon which the award is based where required or permitted by those rules, and any calculation of damages awarded where applicable. The arbitrator will have the same authority to award relief on an individual basis that a judge in a court of law would have, subject to this Arbitration Agreement, the applicable arbitration rules, and applicable law. The award will be final and binding, subject to any review permitted by applicable law. Any judgment upon an arbitration award may be entered in a court of competent jurisdiction.",
        { h: "20.7 Settlement Offers" },
        "To the extent permitted by applicable law and the applicable arbitration rules, at least ten (10) calendar days before the date set for the arbitration hearing, either party may serve a written offer of judgment on the other party to allow judgment on specified terms.",
        "If the offer is accepted, the offer and proof of acceptance may be submitted to the arbitration provider for entry in accordance with the applicable arbitration rules. If the offer is not accepted before the arbitration hearing or within thirty (30) calendar days after it is made, whichever occurs first, the offer will be deemed withdrawn.",
        "If an offer made by one party is not accepted by the other party and the other party fails to obtain an award more favorable than the offer, then, to the extent permitted by applicable law and the applicable arbitration rules, the other party will not recover its otherwise recoverable costs incurred after the date of the offer and will be responsible for the offering party’s recoverable costs, including arbitration-provider fees, incurred after the date of the offer.",
        "The offer may not be introduced as evidence in the arbitration except to the extent necessary to determine costs or fees after the arbitrator has determined the merits.",
        { h: "20.8 Waiver of Jury Trial" },
        "YOU AND THE PixyDust PARTIES WAIVE, TO THE FULLEST EXTENT PERMITTED BY LAW, ANY CONSTITUTIONAL OR STATUTORY RIGHT TO HAVE CLAIMS SUBJECT TO THIS ARBITRATION AGREEMENT DECIDED IN COURT BY A JUDGE OR JURY.",
        "You and the PixyDust Parties instead agree to have claims and disputes subject to this Arbitration Agreement resolved through arbitration. Arbitration differs from litigation in court and is generally subject to more limited judicial review. Where litigation concerning enforcement or vacatur of an arbitration award is permitted, you and the PixyDust Parties waive the right to a jury trial to the fullest extent permitted by law.",
        { h: "20.9 Waiver of Class, Collective, Consolidated, or Representative Actions" },
        "ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS, COLLECTIVE, CONSOLIDATED, PRIVATE ATTORNEY GENERAL, OR REPRESENTATIVE BASIS, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.",
        "For the avoidance of doubt, PixyDust does not consent to class, collective, consolidated, private attorney general, or representative arbitration under these Terms.",
        "Claims of more than one user or customer may not be arbitrated jointly or consolidated unless the parties expressly agree otherwise. For clarity, the administration of multiple individual arbitration demands under any applicable mass-arbitration or coordinated-filing procedures of the arbitration provider will not, by itself, constitute or authorize joint, consolidated, class, collective, private attorney general, or representative arbitration of the merits. Each claim subject to arbitration will remain an individual claim unless the parties expressly agree otherwise.",
        "This provision does not prevent participation in a class-wide settlement.",
        "Except where applicable law requires otherwise, disputes concerning the interpretation, applicability, or enforceability of this class, collective, consolidated, private attorney general, or representative action waiver will be determined by the arbitrator in accordance with Section 20.1.",
        "If this waiver is limited, voided, or found unenforceable as to a particular proceeding, and that determination permits the proceeding to continue on a class, collective, consolidated, private attorney general, or representative basis, then the agreement to arbitrate will not apply to that proceeding. Any such proceeding must proceed in a court of competent jurisdiction and not in arbitration.",
        { h: "20.10 Right to Waive" },
        "Any right or limitation under this Arbitration Agreement may be waived by the party against whom the claim is asserted with respect to a particular claim. Such waiver does not waive or affect any other portion of this Arbitration Agreement.",
        { h: "20.11 Small Claims Court" },
        "Notwithstanding the foregoing, either you or the PixyDust Parties may bring an individual action in small claims court where the dispute qualifies.",
        { h: "20.12 Arbitration Agreement Survival" },
        "This Arbitration Agreement survives termination of your relationship with PixyDust or the PixyDust Parties, including termination or deletion of your account, revocation of consent, or any other action by you to end your participation in or use of the Applications.",
      ],
    },
    {
      id: "other",
      title: "21. Other Terms",
      body: [
        { h: "21.1 Entire Agreement" },
        "These Terms and any supplemental terms applicable to your use of the Applications constitute the complete agreement between you and PixyDust concerning the Applications and supersede prior agreements concerning the same subject matter, except as otherwise expressly provided.",
        { h: "21.2 Choice of Law" },
        "Except to the extent overridden by U.S. federal law or mandatory applicable law, these Terms and claims or disputes arising out of or relating to these Terms or their subject matter are governed by the laws of the State of New York, without regard to its conflict-of-laws principles.",
        { h: "21.3 Exclusive Venue" },
        "To the extent that these Terms or applicable law permit a dispute or proceeding to be brought before a court, you and PixyDust consent to the exclusive jurisdiction and venue of the courts specified in this Section. This includes proceedings for provisional relief permitted under Section 20.1 and proceedings relating to the Arbitration Agreement or an arbitration award. Where federal subject-matter jurisdiction exists, the exclusive jurisdiction and venue will be the United States District Court for the Southern District of New York. Otherwise, the exclusive jurisdiction and venue will be the Supreme Court of the State of New York, New York County. The foregoing is subject to any contrary requirement of applicable law.",
        { h: "21.4 No Waiver" },
        "PixyDust's failure to enforce any provision of these Terms does not constitute a waiver of that provision or any other right.",
        { h: "21.5 Severability" },
        "If any provision of these Terms is determined to be invalid, illegal, or unenforceable, that provision will be enforced to the maximum extent permitted by law or severed to the minimum extent necessary, and the remaining provisions will remain in full force and effect.",
        { h: "21.6 Assignment" },
        "You may not assign or transfer these Terms or any rights or obligations under them without PixyDust's prior written consent. Any attempted assignment or transfer in violation of this Section is null and void.",
        "PixyDust may assign or transfer these Terms or any of its rights or obligations under them, in whole or in part, and may provide or arrange for the provision of the Applications through another entity, including in connection with a merger, acquisition, corporate reorganization, financing, sale of assets, or transfer of the Applications or relevant business, subject to applicable law.",
        { h: "21.7 Force Majeure" },
        "PixyDust will not be responsible for delay, interruption, failure, or inability to perform resulting from circumstances beyond its reasonable control, including natural disasters, acts of government, war, terrorism, civil unrest, labor disputes, internet or telecommunications failures, power outages, cyberattacks, cloud or infrastructure failures, or failures, restrictions, outages, policy changes, or discontinuation by Third-Party Providers, APIs, hosting providers, payment providers, or other third-party services.",
        { h: "21.8 Electronic Communications and Notices" },
        "You consent to receive notices and communications relating to the Applications and these Terms electronically, including through the Applications, by email, or through other contact information associated with your account, to the extent permitted by applicable law.",
        "You are responsible for maintaining accurate contact information associated with your account.",
        "Legal notices to PixyDust should be sent to: legal@pixydust.com",
        { h: "21.9 Relationship of the Parties" },
        "Nothing in these Terms creates a partnership, joint venture, employment, agency, fiduciary, franchise, or other similar relationship between you and PixyDust.",
        { h: "21.10 Headings" },
        "Section titles and headings are provided for convenience and do not affect interpretation of these Terms.",
        { h: "21.11 Survival" },
        "Any provisions that by their nature should survive termination of these Terms, termination or deletion of your account, or cessation of your use of the Applications will survive, including provisions concerning ownership, rights and licenses granted to PixyDust or intended to survive, indemnification, warranty disclaimers, limitations of liability, dispute resolution, and accrued rights, remedies, and obligations.",
        { h: "21.12 Supplemental Terms" },
        "Certain Applications, AI models, features, promotions, products, enterprise offerings, or other services may be subject to additional terms presented to you in connection with those offerings.",
        "If supplemental terms conflict with these Terms, the supplemental terms will control with respect to the specific feature, product, or service to which they apply, unless expressly stated otherwise.",
        { h: "21.13 California Consumer Rights Notice" },
        "If you are a California resident, in accordance with California Civil Code § 1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting them in writing at 1625 North Market Blvd., Suite N 112, Sacramento, CA 95834, or by telephone at (800) 952-5210.",
        { h: "21.14 Contact Us" },
        "Questions regarding these Terms or the Applications may be directed to: support@pixydust.com",
        "PixyDust reserves all rights not expressly granted under these Terms.",
      ],
    },
  ],
};
