// PixyDust Terms of Service — counsel-supplied text, reproduced VERBATIM.
// Do not paraphrase, summarise, re-order, or "tidy" any wording here: this is a
// binding legal document and the numbering is cross-referenced internally
// (e.g. Section 20, Section 12.5). Only the counsel-approved source may change it.
import type { LegalDoc } from "./legal";

export const TERMS: LegalDoc = {
  current: "terms",
  kicker: "Legal · governing your use of PixyDust",
  title: "PixyDust Terms of Service",
  subtitle: "These Terms of Service govern your access to and use of PixyDust.",
  lastUpdated: "September 4, 2026",
  numbered: true,
  sections: [
    {
      id: "relationship",
      title: "1. Our Relationship",
      body: [
        "These Terms of Service (“Terms”) govern your access to and use of PixyDust, including our websites, applications, software, features, AI models and tools, augmented reality features, content, and related services (collectively, the “Applications”). These Terms constitute a legally binding agreement between you and White Glove Media, LLC (“WGM,” “we,” “us,” or “our”).",
        "By accessing or using the Applications, creating an account, purchasing or using Credits, or otherwise indicating your acceptance of these Terms, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Applications.",
        "Our Privacy Policy describes how we collect, use, disclose, and otherwise process personal information in connection with the Applications. The Privacy Policy is a notice and is not part of these Terms.",
        "ARBITRATION AND CLASS ACTION/JURY TRIAL WAIVER NOTICE: THESE TERMS CONTAIN A BINDING ARBITRATION AGREEMENT IN SECTION 20. EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN SECTION 20, YOU AND WGM AGREE TO RESOLVE DISPUTES THROUGH BINDING INDIVIDUAL ARBITRATION RATHER THAN IN COURT. YOU ALSO WAIVE THE RIGHT TO A JURY TRIAL AND THE RIGHT TO PARTICIPATE IN A CLASS, COLLECTIVE, CONSOLIDATED, OR REPRESENTATIVE ACTION OR ARBITRATION. PLEASE READ SECTION 20 CAREFULLY.",
      ],
    },
    {
      id: "changes",
      title: "2. Changes to the Applications or Terms",
      body: [
        { h: "2.1 Changes to the Applications" },
        "We may modify, update, add, remove, suspend, discontinue, or otherwise change any part of the Applications, including any features, functionality, AI models, model versions, integrations, tools, content, availability, usage limits, or pricing applicable to future purchases or uses, at any time, with or without notice, subject to applicable law. We do not guarantee that any particular feature, AI model, model version, integration, tool, or functionality will remain available.",
        { h: "2.2 Changes to These Terms" },
        "We may update or modify these Terms from time to time, including to reflect changes to the Applications, the way we operate or provide them, our business practices, or applicable legal, regulatory, security, or operational requirements. When we make material changes, we will provide reasonable advance notice where required or appropriate, such as through the Applications, by email, or by other reasonable means.",
        "The updated Terms will become effective on the date specified in the updated Terms or accompanying notice. Your continued use of the Applications after the updated Terms become effective constitutes your acceptance of the updated Terms, except where applicable law requires additional notice or affirmative consent.",
      ],
    },
    {
      id: "your-rights",
      title: "3. Your Rights & Use of Our Applications",
      body: [
        "Our Applications let you create, generate, upload, record, edit, process, view, publish, and share content, including through artificial intelligence, augmented reality, and other tools and features that we may make available from time to time.",
        "Subject to your compliance with these Terms, WGM grants you a limited, non-assignable, non-exclusive, revocable, and non-sublicensable right to access and use the Applications according to these Terms. WGM reserves all rights not expressly granted to you.",
        "By accessing or using our Applications, you represent, warrant, and agree that:",
        {
          clauses: [
            "(a) You have the legal capacity and authority to enter into a legally binding contract with WGM.",
            "(b) You are at least eighteen (18) years old and have reached the age of legal majority in your jurisdiction, if the age of legal majority in your jurisdiction is higher than eighteen (18). The Applications are not intended for or available to minors.",
            "(c) You are not a convicted sex offender.",
            "(d) You will abide by these Terms and all applicable local, state, national, and international laws, rules, and regulations.",
            "(e) You are not prohibited from accessing or using the Applications under the laws of the United States or any other applicable jurisdiction, including applicable trade sanctions and export control laws, and you are not subject to sanctions or other restrictions that would prohibit WGM from providing the Applications to you.",
            "(f) You will only upload, submit, record, generate, publish, share, or otherwise use content through the Applications if you have all rights, licenses, permissions, releases, and consents necessary to do so, including any rights relating to intellectual property, privacy, publicity, name, image, likeness, voice, recording, or other applicable rights.",
            "(g) You will not use the Applications in a manner that is unlawful, fraudulent, deceptive, harmful, abusive, harassing, infringing, or that violates the rights of any person or entity.",
            "(h) You will use any augmented reality, recording, camera, location-based, or similar features responsibly and safely, remain aware of your surroundings, and comply with applicable laws while using such features.",
            "(i) You are responsible for maintaining the security and confidentiality of your account and credentials and, to the extent permitted by applicable law, for activity conducted through your account.",
            "(j) WGM has not previously suspended or terminated your account for violations of these Terms, unless WGM has expressly authorized you to create or use another account.",
          ],
        },
        "If we learn or reasonably believe that you do not meet the applicable minimum age requirements, we may suspend or terminate your account or access to the Applications and take other appropriate measures consistent with applicable law.",
        "If you are using the Applications on behalf of a business, organization, or other legal entity:",
        {
          clauses: [
            "(i) “you” and “your” encompass both you as an individual and that entity;",
            "(ii) you represent and warrant that you are an authorized representative of the entity with the authority to legally bind the entity to these Terms, and you agree to these Terms on behalf of the entity; and",
            "(iii) the entity is legally and financially responsible for your access to and use of the Applications and for access to and use of the Applications by its employees, agents, contractors, and other persons acting on its behalf or through its account.",
          ],
        },
        "Except as expressly provided in these Terms, these Terms do not establish or grant rights or remedies to any third-party beneficiaries.",
      ],
    },
    {
      id: "accounts",
      title: "4. Accounts and Account Security",
      body: [
        "Certain features of the Applications may require you to create or maintain an account. You agree to provide accurate, current, and complete information in connection with your account and to keep such information reasonably current.",
        "You are responsible for maintaining the confidentiality and security of your login credentials and for taking reasonable steps to prevent unauthorized access to your account.",
        "You may not sell, transfer, license, rent, or otherwise provide your account or account credentials to another person except as expressly authorized by WGM.",
        "You may not permit any person who does not satisfy the minimum age requirements in Section 3 to access or use the Applications through your account.",
        "You agree to promptly notify WGM at support@pixydust.com if you know or reasonably suspect that your account or credentials have been compromised or used without authorization.",
        "To the extent permitted by applicable law, you are responsible for activity occurring through your account, including purchases and use of Credits, except to the extent such activity results directly from WGM's breach of its legal obligations.",
        "We may require you to verify information associated with your account, reset credentials, or take other security measures where we reasonably believe doing so is necessary to protect you, WGM, other users, or the Applications.",
      ],
    },
    {
      id: "user-content",
      title: "5. Applications & User Content",
      body: [
        { h: "5.1 User Content" },
        "The Applications may allow you to create, upload, submit, record, capture, generate, process, publish, transmit, or share content (“User Content”).",
        "User Content may include:",
        {
          clauses: [
            "(a) photos, video, audio, recordings, and other content captured through the Applications (“Captured Content”);",
            "(b) prompts, instructions, text, images, audio, video, files, data, reference materials, and other content you submit to AI-powered features (“Inputs”);",
            "(c) images, video, audio, text, and other content generated or returned through AI-powered features in response to Inputs (“Outputs”); and",
            "(d) User Content you choose to publish, share, or otherwise make available to other users or the public through the Applications (“Public Content”).",
          ],
        },
        { h: "5.2 Ownership of Your Content and License to WGM" },
        "As between you and WGM, you retain your ownership rights in User Content that you own, subject to the licenses and rights granted in these Terms.",
        "When you create, upload, submit, record, capture, generate, process, publish, transmit, or share User Content through the Applications, you grant WGM certain rights and licenses to use that User Content as described in Section 6 (Rights You Grant Us).",
        "As between you and WGM, WGM does not claim ownership of your Inputs or Outputs. To the extent permitted by applicable law, and subject to any rights of WGM or third parties in underlying materials, models, technology, or content, you may use Outputs generated for you for lawful purposes, including commercial purposes.",
        "Your rights, if any, in Outputs generated for you are not terminated solely because you cancel a subscription or terminate your account. Subject to these Terms and applicable law, you may transfer or sublicense those rights to clients or other third parties.",
        "Nothing in these Terms represents or guarantees that any Output is eligible for copyright, trademark, patent, or other intellectual property protection.",
        { h: "5.3 Responsibility for User Content; Rights, Permissions and Safety" },
        "You are solely responsible for User Content that you create, capture, submit, upload, record, generate, publish, share, distribute, or otherwise use through or in connection with the Applications.",
        "You represent and warrant that you own or otherwise have obtained all rights, licenses, permissions, releases, and consents necessary for you to provide User Content to the Applications and to grant WGM the rights and licenses granted under these Terms.",
        "Without limiting the foregoing, if User Content includes or depicts any person's name, image, likeness, voice, performance, persona, or other identifiable attributes, or includes recordings of or biometric information relating to any person, you represent and warrant that you have obtained all rights, licenses, permissions, releases, and consents necessary to provide such User Content to the Applications and to permit the uses authorized by these Terms, including, where applicable, commercial, advertising, promotional, and marketing uses, without WGM being required to obtain additional permission from or pay compensation to that person or any other third party.",
        "If User Content contains music or other audio content, you represent and warrant that you have obtained all rights, licenses, permissions, and clearances necessary for the uses authorized by these Terms, including, where applicable, rights relating to musical compositions, sound recordings, synchronization, reproduction, distribution, public performance, and communication to the public.",
        "You further represent and warrant that WGM's exercise of the rights and licenses granted by you under these Terms will not infringe, misappropriate, or otherwise violate any third party's copyright, trademark, patent, rights of publicity, privacy, or personality, contractual rights, or other intellectual property, proprietary, or personal rights.",
        "You must never endanger yourself or others in the pursuit of capturing, creating, recording, generating, or sharing User Content through the Applications.",
        "Additional requirements applicable to augmented reality, recording, camera, location-based, and social features are described in Section 9 (AR, Recording and Social Features).",
        { h: "5.4 Compliance and Retention" },
        "By using the Applications, you agree to comply with these Terms. If you violate or we reasonably suspect that you have violated these Terms, we may retain User Content and data or other information relating to the actual or suspected violation and may disclose relevant retained information to third parties, subject to applicable law.",
        "Additional provisions regarding monitoring, moderation, reporting, retention, and disclosure are set forth in Section 13 (Monitoring, Moderation and Reporting).",
        { h: "5.5 Storage and Availability" },
        "Your User Content may become unavailable for any number of reasons, including operational or technical failures. We do not guarantee that User Content will always remain available.",
        "You should maintain separate copies of User Content that is important to you.",
        "We may review, restrict, remove, or delete User Content from the Applications at any time, subject to applicable law and these Terms.",
        "We generally cannot remove copies of User Content that you or others have shared, downloaded, copied, transmitted, or stored outside the Applications.",
        { h: "5.6 Similar or Identical Outputs" },
        "Because of the nature of generative artificial intelligence, Outputs may not be unique. Other users may receive Outputs that are identical or similar to Outputs generated for you.",
        "You acknowledge and agree that similarity between Outputs does not, by itself, give you any rights or claims against WGM or another user.",
        { h: "5.7 Third-Party Content" },
        "The Applications may display, include, provide access to, or otherwise make available data, information, features, websites, applications, content, products, or services provided by third parties (“Third-Party Content”).",
        "If you choose to access or use Third-Party Content made available through the Applications, your access to and use of that Third-Party Content are subject to the applicable third party’s terms, policies, and conditions, to the extent applicable.",
        "To the maximum extent permitted by applicable law, WGM and its affiliates are not responsible for the terms, policies, practices, acts, or omissions of third parties, and are not responsible for evaluating, verifying, endorsing, or guaranteeing Third-Party Content. WGM and its affiliates disclaim responsibility or liability arising from or relating to Third-Party Content.",
        "Certain features of the Applications may also use or depend upon third-party artificial intelligence models, APIs, infrastructure, software, and other services. Additional terms concerning Third-Party AI Providers and Third-Party Services are set forth in Section 11 (Third-Party AI Models and Services).",
        { h: "5.8 Advertising and Promotions" },
        "We may display advertisements, promotions, sponsored content, offers, or other commercial content within or in connection with the Applications, including personalized offers, subject to applicable law.",
        "Your interactions with third-party advertisers, sponsors, or promotional partners, including any purchases, transactions, promotions, or other dealings with them, are solely between you and the applicable third party. To the maximum extent permitted by applicable law, WGM is not responsible or liable for the acts, omissions, products, services, representations, offers, or other activities of third-party advertisers, sponsors, or promotional partners.",
      ],
    },
    {
      id: "rights-you-grant",
      title: "6. Rights You Grant Us",
      body: [
        { h: "6.1 User Content" },
        "For User Content that you create, record, capture, upload, submit, generate, process, or otherwise provide through the Applications, including Captured Content, Inputs, and Outputs, you grant WGM and our affiliates a worldwide, non-exclusive, royalty-free, sublicensable license to host, store, cache, reproduce, process, analyze, transmit, modify, adapt, and otherwise use such User Content as reasonably necessary to operate, provide, secure, maintain, support, troubleshoot, develop, and improve the Applications and other products and services of WGM and its affiliates, and to provide the functionality you request.",
        "WGM may use User Content, including Captured Content, Inputs, and Outputs, to develop, train, test, evaluate, enhance, improve, and otherwise support the Applications, artificial intelligence and machine-learning models, algorithms, technologies, products, and services of WGM and its affiliates, subject to applicable law and our Privacy Policy.",
        "Deletion or removal of User Content will not require WGM to reverse, retrain, modify, or otherwise alter any artificial intelligence or machine-learning model, algorithm, technology, product, or service that was developed, trained, tested, evaluated, enhanced, or improved using such User Content before its deletion or removal, to the extent permitted by applicable law.",
        "If User Content is intentionally made publicly available through the Applications, the additional rights and licenses applicable to Public Content under Section 6.3 will apply.",
        { h: "6.2 Inputs and Outputs" },
        "In addition to the rights granted under Section 6.1, where you use artificial intelligence or machine-learning functionality made available through the Applications, you authorize WGM, our affiliates, our service providers, and Third-Party AI Providers to receive, host, store, reproduce, transmit, process, analyze, modify as technically necessary, and otherwise use your Inputs, Outputs, and related User Content as reasonably necessary to process your requests, generate and deliver Outputs, provide the AI functionality you request, operate and support such functionality, enforce applicable usage requirements, prevent fraud, abuse, and misuse, and maintain the safety, security, and integrity of the Applications.",
        "Your use of third-party models, technologies, or services through the Applications may also involve processing of Inputs, Outputs, or related User Content by Third-Party AI Providers, subject to Section 11 and our Privacy Policy.",
        "Nothing in this Section limits the operational, development, training, testing, evaluation, enhancement, or improvement rights granted to WGM under Section 6.1.",
        { h: "6.3 Public Content" },
        "If you intentionally publish, post, share, submit to a public gallery, community, showcase, contest, campaign, promotional program, or otherwise make User Content, including any Captured Content, Input, or Output, publicly available through the Applications, you grant WGM, our affiliates, and our business partners a worldwide, unrestricted, non-exclusive, royalty-free, irrevocable, perpetual, sublicensable, and transferable right and license to host, store, cache, analyze, transmit, use, display, reproduce, modify, adapt, edit, translate, create derivative works from, distribute, monetize, promote, exhibit, broadcast, syndicate, synchronize, overlay graphics and auditory effects on, publicly perform, publicly display, communicate, make available, and otherwise use such Public Content, in any form and in any media format or distribution method currently known or later developed, for commercial and non-commercial purposes, including to operate, develop, provide, promote, market, and improve the Applications and to develop new products and services.",
        "By making User Content publicly available through the Applications, you also grant other users of the Applications a worldwide, non-exclusive, royalty-free license to access, view, use, reproduce, download, share, modify, adapt, remix, regenerate from, and create derivative works from such Public Content through or in connection with the functionality made available by the Applications, subject to these Terms and applicable law.",
        "The rights granted to other users under this Section are limited to uses authorized by these Terms and the functionality made available by the Applications and do not include any rights in underlying third-party content or materials beyond the rights you are authorized to grant.",
        "The license granted to WGM, our affiliates, and our business partners under this Section applies to Public Content as a whole and, without limitation, to the separate video, images, sound recordings, musical compositions, and other elements contained in Public Content. The license also includes the right to use any name, username, profile information, image, likeness, and voice included in, depicted in, or intentionally made publicly available in connection with such Public Content to identify, attribute, display, promote, market, monetize, or feature the Public Content, the Applications, WGM, and its products and services. WGM has no obligation to attribute Public Content to you or any other person unless required by applicable law. You will not be entitled to compensation for WGM's, our affiliates', or our business partners' use of Public Content as authorized by this Section.",
        "The rights and licenses granted to WGM, our affiliates, and our business partners under this Section are irrevocable and perpetual and will survive the deletion or removal of Public Content from the Applications, to the extent permitted by applicable law.",
        "Deletion or removal of Public Content from the Applications will not terminate or revoke any rights or licenses previously granted or exercised with respect to such Public Content, including where the Public Content has been accessed, viewed, reproduced, downloaded, shared, copied, distributed, modified, adapted, remixed, regenerated from, incorporated into derivative works, or otherwise used by other users while the Public Content was publicly available, subject to these Terms and applicable law. Deletion or removal also will not require WGM to remove copies retained in routine backups or where continued retention is required or permitted by applicable law.",
        "Except as otherwise expressly authorized by these Terms, WGM will not use private Inputs, private Outputs, private Captured Content, or other private User Content in external advertising or promotional materials without your consent.",
        { h: "6.4 Moral Rights" },
        "To the extent permitted by applicable law, you irrevocably waive, and agree not to assert against WGM, its affiliates, or any other person or entity authorized to exercise rights granted under these Terms, any moral rights or equivalent rights you may have in User Content to the extent necessary for WGM or such person or entity to exercise the rights and licenses granted under these Terms.",
        { h: "6.5 Feedback" },
        "We value feedback and suggestions from users. If you provide ideas, feedback, recommendations, or suggestions regarding the Applications, WGM may use them without compensation, restriction, or obligation to you. You agree that WGM may own and use products, services, features, improvements, or other materials developed based upon or incorporating such feedback, subject to applicable law.",
      ],
    },
    {
      id: "ip",
      title: "7. PixyDust and Application Intellectual Property",
      body: [
        "The content, software, images, text, graphics, illustrations, logos, icons, photographs, audio, videos, music, branding, works of authorship, features, models, technology, overall visual and functional design of the Applications, and other proprietary materials and technology owned by or licensed to WGM, our affiliates, licensors, or service providers (collectively, “Application Content”), and all patents, trademarks, service marks, copyrights, and other intellectual property rights relating to the Applications or Application Content, are owned by or licensed to WGM, our affiliates, licensors, or service providers, as applicable, and are protected by applicable intellectual property laws.",
        "Except for the limited rights expressly granted under these Terms, you receive no right, title, or interest in or to the Applications or Application Content. The use of Application Content for any purpose not expressly authorized by these Terms is prohibited. Application Content may not be used, downloaded, copied, reproduced, modified, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited except as expressly permitted by these Terms or with the prior written consent of WGM or the applicable rights holder.",
        "WGM and the applicable rights holders reserve all rights not expressly granted.",
      ],
    },
    {
      id: "acceptable-use",
      title: "8. Acceptable Use and Prohibited Conduct",
      body: [
        "You may not, and may not attempt to, assist, encourage, or enable another person to:",
        {
          clauses: [
            "(a) duplicate, reverse engineer, modify, decompile, decode, disassemble, or create derivative works from the Applications, or derive, attempt to derive, or extract source code, models, algorithms, model weights, underlying components, or other non-public technology of the Applications, except where applicable law expressly prohibits this restriction;",
            "(b) circumvent, disable, evade, interfere with, or defeat security, safety, moderation, authentication, rate-limit, payment, Credit, access-control, watermarking, provenance, or content-authenticity mechanisms;",
            "(c) probe, scan, or test vulnerabilities of the Applications, systems, or networks without WGM's prior written authorization;",
            "(d) use the Applications in violation of applicable law or regulation;",
            "(e) infringe or misappropriate intellectual property, privacy, publicity, personality, confidentiality, contractual, or other rights;",
            "(f) create, upload, distribute, solicit, or facilitate child sexual abuse material, sexual exploitation of minors, grooming, or other unlawful sexual content involving minors;",
            "(g) create or distribute non-consensual intimate imagery or sexually explicit material depicting an identifiable person without legally sufficient authorization;",
            "(h) threaten, stalk, harass, bully, abuse, exploit, or endanger another person;",
            "(i) deceptively impersonate another person or create content intended to mislead others about a person's identity, statements, conduct, or endorsement in violation of applicable law;",
            "(j) commit or facilitate fraud, phishing, scams, identity theft, or other deceptive practices;",
            "(k) introduce malware, malicious code, viruses, or other harmful technology;",
            "(l) access, scrape, collect, or extract data from the Applications by automated means except as expressly authorized by WGM;",
            "(m) manipulate, counterfeit, duplicate, exploit, or circumvent Credits, billing systems, usage limitations, promotions, or technical restrictions;",
            "(n) use Outputs or access to the Applications to develop, train, fine-tune, distill, benchmark for competitive replication, or otherwise create or improve a competing artificial intelligence model or service, except with WGM's prior written permission;",
            "(o) use the Applications to violate applicable export controls, sanctions, or other trade restrictions;",
            "(p) use the Applications in a manner that could damage, disable, overburden, disrupt, or materially impair the Applications or interfere with another user's use;",
            "(q) access or use the Applications other than as permitted by these Terms; or",
            "(r) encourage, direct, or assist anyone else to engage in prohibited conduct.",
          ],
        },
        "WGM may establish additional acceptable-use, safety, model-specific, or community guidelines from time to time.",
      ],
    },
    {
      id: "ar-recording",
      title: "9. Augmented Reality, Recording and Social Features",
      body: [
        { h: "9.1 Recording and Capturing Content" },
        "Certain Applications may allow you to photograph, film, record, capture, publish, or share people, places, audio, video, or other content. You are responsible for complying with applicable recording, privacy, surveillance, publicity, property, and other laws and for obtaining any permissions or consents required before recording, capturing, publishing, or sharing such content.",
        { h: "9.2 Safety and Surroundings" },
        "Never endanger yourself or others in pursuit of capturing content or using the Applications.",
        "When using augmented reality, camera, recording, location-based, or similar functionality, you are responsible for remaining aware of your surroundings and using the Applications safely.",
        "Do not use the Applications in a manner that distracts you while driving, operating machinery, or engaging in another activity requiring your attention. You are responsible for complying with applicable laws, property restrictions, and safety requirements and for avoiding trespass or entry into unsafe or restricted areas.",
        { h: "9.3 Social and Community Features" },
        "The Applications may allow users to maintain profiles, publish User Content, communicate with others, comment, follow users, collaborate, or otherwise participate in social or community features. You are responsible for your interactions with other users. WGM does not guarantee the identity, conduct, statements, accuracy, or intentions of other users and is not responsible for interactions between users except to the extent required by applicable law. We may moderate, restrict, remove, or disable access to User Content or social functionality in accordance with these Terms.",
      ],
    },
    {
      id: "ai-features",
      title: "10. Artificial Intelligence Features and Outputs",
      body: [
        { h: "10.1 Generative AI" },
        "Certain Applications use artificial intelligence and machine-learning technologies to generate or transform images, videos, audio, text, and other content based upon Inputs. You acknowledge that artificial intelligence and machine-learning technologies are probabilistic and evolving and may produce unexpected results.",
        { h: "10.2 No Guarantee Regarding Outputs" },
        "WGM does not represent or warrant that Outputs will be accurate, complete, reliable, factual, error-free, appropriate, original, unique, non-infringing, or suitable for any particular purpose.",
        "Outputs may contain errors, inaccuracies, artifacts, offensive material, or content resembling material created for or by other users or third parties.",
        { h: "10.3 Review Before Use" },
        "You are responsible for evaluating Outputs before using, publishing, distributing, relying upon, or commercially exploiting them. You should not rely upon Outputs as the sole source of truth or as a substitute for professional judgment where accuracy is important.",
        { h: "10.4 Professional and High-Impact Decisions" },
        "Outputs are not intended to constitute medical, legal, financial, investment, accounting, or other professional advice. In addition, you may not use the Applications to make or materially assist in making decisions concerning another person's eligibility for, access to, or receipt of employment, housing, credit, insurance, education, government benefits or services, or other high-impact opportunities or services, where such use is prohibited or restricted by applicable law.",
        { h: "10.5 Intellectual Property and Outputs" },
        "WGM does not guarantee that an Output is eligible for intellectual property protection or that your use of an Output will not infringe, misappropriate, or otherwise violate third-party rights.",
        "WGM does not review, verify, or perform intellectual property, rights-clearance, or other legal clearance searches with respect to Inputs or Outputs. You are responsible for determining whether your intended use of an Output is lawful and for obtaining any rights or permissions necessary for such use.",
        { h: "10.6 AI-Generated Content Disclosures" },
        "When required by applicable law, you must clearly and conspicuously disclose that an Output was generated or manipulated using artificial intelligence or otherwise comply with applicable requirements concerning the identification, labeling, or disclosure of AI-generated or AI-manipulated content.",
        { h: "10.7 Watermarks, Content Credentials and Provenance Information" },
        "WGM may apply or embed watermarks, Content Credentials, provenance metadata, digital signatures, fingerprints, or other identifiers or technical measures in or in connection with Outputs to identify, authenticate, trace, or provide information concerning the source, creation, modification, or use of such Outputs. You may not remove, obscure, alter, falsify, circumvent, or interfere with any such watermark, Content Credential, provenance information, digital signature, fingerprint, identifier, or technical measure except as expressly permitted by WGM.",
      ],
    },
    {
      id: "third-party",
      title: "11. Third-Party AI Models and Services",
      body: [
        { h: "11.1 Third-Party Providers" },
        "Certain features of the Applications may use or depend upon artificial intelligence models, APIs, cloud infrastructure, hosting providers, payment providers, data sources, software, or other products and services supplied by third parties (“Third-Party Services”). AI models and related services supplied by third parties are referred to as “Third-Party AI Providers.”",
        { h: "11.2 Provider Terms" },
        "Your use of a particular Third-Party Service or AI model may be subject to additional restrictions, acceptable-use policies, licenses, or terms imposed by the applicable provider.",
        "Where a Third-Party AI Provider imposes restrictions applicable to your use of a particular model or feature, you agree to comply with those restrictions.",
        { h: "11.3 Model Availability" },
        "WGM may add, remove, replace, restrict, suspend, modify, or discontinue access to any Third-Party AI Provider, model, model version, integration, or feature at any time. Purchase or possession of Credits does not guarantee continued access to any particular AI model, model version, provider, feature, generation method, speed, resolution, capability, or functionality.",
        { h: "11.4 Third-Party Changes and Outages" },
        "Third-Party Services may experience outages, delays, capacity constraints, policy changes, technical failures, model changes, price changes, or discontinuation outside WGM's control.",
        "WGM does not guarantee the continued availability, performance, latency, throughput, accuracy, or quality of any Third-Party Service.",
        { h: "11.5 Third-Party Content" },
        "The Applications may display, include, link to, integrate with, or provide access to websites, applications, accounts, advertisements, promotions, data, information, content, products, or services supplied or operated by third parties. If you access, use, interact with, purchase from, or connect your account to a third-party website, application, account, product, or service, your relationship with that third party may be governed by its own terms, policies, and practices.",
        "Except to the extent required by applicable law, WGM does not control, endorse, evaluate, verify, guarantee, or assume responsibility for any third-party website, application, account, advertisement, promotion, content, product, service, or other Third-Party Service, or for the availability, accuracy, security, privacy practices, products, services, representations, or conduct of any third party",
      ],
    },
    {
      id: "credits",
      title: "12. Credits, Purchases, Pricing and Refunds",
      body: [
        { h: "12.1 Credits" },
        "PixyDust may allow you to purchase Credits separately, obtain Credits as part of a subscription, or receive promotional, complimentary, bonus, trial, or other Credits (collectively, “Credits”). Credits purchased separately or in addition to a subscription may be referred to as “Add-On Credits.”",
        "Credits represent a limited contractual right to initiate eligible generation or processing requests and receive the resulting Outputs or other applicable digital content or functionality, in accordance with these Terms. Credits are not legal tender, currency, cryptocurrency, stored value, a bank deposit, security, or other financial instrument. Credits have no cash value, do not accrue interest, and may not be redeemed for cash except where required by applicable law. Credits may not be sold, transferred, assigned, exchanged, or traded except as expressly authorized by WGM.",
        "Access to the Applications may be available without charge. Certain generation, processing, or other functionality requires Credits. When you initiate functionality requiring Credits, the applicable number of Credits will be deducted from your account, and WGM will process the applicable request and, where applicable, provide the resulting Output.",
        "WGM's systems and records will determine Credit balances, usage, deductions, and transactions, absent manifest error.",
        { h: "12.2 Credit Costs" },
        "The number of Credits required to use a feature or generate an Output may vary depending upon factors such as the AI model, feature, duration, resolution, quality, settings, computational requirements, or other parameters. WGM may change the number of Credits required for future uses of a feature or model. Changes to Credit costs will apply prospectively and will not retroactively deduct additional Credits for completed transactions.",
        { h: "12.3 Pricing and Payment" },
        "You agree to pay all amounts presented to you at the time of purchase, including applicable taxes and fees. Payments may be processed by third-party payment providers and may be subject to their terms. We may correct pricing, billing, or technical errors and may cancel or reverse transactions resulting from obvious errors, fraud, abuse, or unauthorized activity, subject to applicable law. You are responsible for maintaining current, complete, and accurate payment information associated with your account. If we are unable to process a payment when due, we may suspend, downgrade, or terminate the applicable subscription or restrict access to subscription benefits until payment is successfully received, subject to applicable law",
        { h: "12.4 Subscriptions and Automatic Renewal" },
        "PixyDust may offer subscription plans that provide access to certain features, functionality, Credits, benefits, or usage allowances during a recurring subscription period. The features, Credits, benefits, usage limits, price, and billing period applicable to your subscription will be disclosed at the time of purchase.",
        "Unless otherwise disclosed at the time of purchase or prohibited by applicable law, subscriptions automatically renew for successive subscription periods until canceled. By purchasing a subscription, you authorize WGM or its payment provider to charge the applicable subscription fees, taxes, and other disclosed charges to your selected payment method at the beginning of each subscription period.",
        "You may cancel your subscription through the cancellation methods made available by WGM. Unless otherwise required by applicable law or expressly stated at the time of purchase, cancellation will take effect at the end of your then-current paid subscription period, and you will retain access to the applicable subscription benefits until that time.",
        "Any subscription upgrade, downgrade, or other plan change will take effect at the time disclosed to you when you make the change. Any applicable charges, Credits, benefits, usage limits, prorations, or other adjustments resulting from the change will be determined and disclosed in accordance with the applicable plan terms and checkout or account interface",
        "WGM may change subscription prices or plan features prospectively upon notice as required by applicable law. Any price change will take effect no earlier than your next applicable renewal period following the effective date of the change, subject to any additional notice or consent required by applicable law.",
        "PixyDust may offer free trials, promotional pricing, or other promotional subscription offers. Any additional terms applicable to an offer will be disclosed when you enroll. If disclosed at enrollment, your subscription will automatically convert to a paid subscription at the applicable price when the trial or promotional period ends unless you cancel before then",
        { h: "12.5 Credit Expiration and Rollover" },
        "Subscription Credits are allocated for each applicable subscription period and do not roll over. Any unused Subscription Credits expire at the end of the applicable monthly billing period or credit allocation period, at which time a new allocation of Subscription Credits will be made in accordance with your subscription plan.",
        "Credits purchased separately as top-ups or add-ons (“Add-On Credits”) are valid for ninety (90) days from the date of purchase. Any unused Add-On Credits expire at the end of that 90-day period.",
        "Promotional, complimentary, bonus, trial, or other non-purchased Credits may expire according to the terms disclosed when they are issued.",
        { h: "12.6 Generation Failures" },
        "If a generation fails because of a qualifying technical failure attributable to the Applications, WGM may, in its discretion or as otherwise required by applicable law, restore the Credits charged for that failed generation. A generation is not necessarily a qualifying technical failure merely because you dislike an Output, an Output does not satisfy your expectations, a prompt is rejected or moderated, a Third-Party AI Provider refuses to process a request, or an Output differs from results produced by another model or service.",
        { h: "12.7 Refunds" },
        "Except where required by applicable law or expressly stated at checkout, subscription fees, purchases of Credits or Add-On Credits, and purchases of other digital products are final and non-refundable. Cancellation of a subscription does not entitle you to a refund or credit for any portion of the then-current subscription period, except where required by applicable law or expressly stated at the time of purchase. Nothing in these Terms limits any refund, withdrawal, cancellation, or other consumer right that cannot lawfully be waived.",
        { h: "12.8 Chargebacks and Payment Abuse" },
        "Fraudulent or abusive chargebacks, payment disputes, payment reversals, or attempts to obtain or use Credits without valid payment may result in suspension or termination of your account, cancellation of Credits, or other appropriate action, subject to applicable law.",
      ],
    },
    {
      id: "moderation",
      title: "13. Monitoring, Moderation and Reporting",
      body: [
        "WGM may, but is not obligated to, monitor, review, screen, filter, restrict, block, or remove Inputs, Outputs, User Content, accounts, or activity for purposes including operating the Applications, enforcing these Terms, protecting users, preventing fraud or abuse, complying with law, and maintaining safety and security. We may use automated systems, human review, or both to identify potentially prohibited or harmful activity. We may block or refuse to process an Input, prevent or restrict generation of an Output, remove User Content, restrict functionality, or suspend or terminate access where we reasonably believe activity violates these Terms, applicable law, provider requirements, or our safety policies.",
        "Where appropriate, we may retain User Content and information relating to suspected violations and disclose relevant information to law enforcement, regulators, rights holders, safety organizations, service providers, or other third parties where permitted or required by applicable law, including as reasonably necessary to protect the safety, rights, or property of WGM, our users, or others; investigate, prevent, remedy, or enforce potential violations of these Terms; address suspected unlawful activity; or detect, prevent, or resolve fraud, abuse, or security concerns.",
        "Users may report content or conduct through mechanisms we make available or by contacting support@pixydust.com. WGM may cooperate with lawful removal requests, intellectual property complaints, safety reports, and requests concerning non-consensual intimate imagery, exploitation, or other unlawful content.",
      ],
    },
    {
      id: "dmca",
      title: "14. Intellectual Property Complaints and DMCA",
      body: [
        "WGM respects intellectual property rights and expects users to do the same. If you believe material available through the Applications infringes your copyright, you may submit a notice under the Digital Millennium Copyright Act (“DMCA”) to our designated agent.",
        "A valid DMCA notice should include the information required by 17 U.S.C. § 512(c)(3), including:",
        {
          clauses: [
            "(a) identification of the copyrighted work claimed to have been infringed;",
            "(b) identification of the allegedly infringing material and information reasonably sufficient to permit WGM to locate it;",
            "(c) your contact information;",
            "(d) a statement that you have a good-faith belief that use of the material is not authorized by the copyright owner, its agent, or law;",
            "(e) a statement, made under penalty of perjury, that the information in your notice is accurate and that you are authorized to act on behalf of the copyright owner; and",
            "(f) your physical or electronic signature.",
          ],
        },
        "DMCA notices should be sent to: dmca@pixydust.com",
        "If your content is removed in response to a DMCA notice, you may have the right to submit a counter-notification as provided by applicable law. WGM may terminate, in appropriate circumstances, accounts of users who are repeat infringers. Claims concerning trademarks or other intellectual property may be submitted to ip@pixydust.com.",
      ],
    },
    {
      id: "indemnification",
      title: "15. Indemnification",
      body: [
        "To the fullest extent permitted by applicable law, you agree to defend, indemnify, and hold harmless WGM, its parents, subsidiaries, affiliates, business partners, licensors, service providers, Third-Party AI Providers, underlying technology providers, and their respective officers, directors, employees, workforce, representatives, agents, and consultants from and against claims, demands, actions, liabilities, losses, damages, judgments, settlements, costs, and expenses, including reasonable attorneys' fees and disbursements, arising out of or relating to:",
        {
          clauses: [
            "(a) your breach or alleged breach of these Terms;",
            "(b) your violation of any representation, warranty, covenant, or obligation under these Terms;",
            "(c) your access to or use of the Applications;",
            "(d) your User Content;",
            "(e) your use, publication, distribution, commercialization, or other exploitation of Outputs;",
            "(f) your infringement, misappropriation, or violation of intellectual property, privacy, publicity, personality, confidentiality, contractual, or other rights of another person or entity;",
            "(g) your violation of applicable law; or",
            "(h) your interactions with other users or third parties through or in connection with the Applications.",
          ],
        },
        "WGM reserves the right, at your expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which case you agree to reasonably cooperate with WGM's defense. You may not settle any matter subject to indemnification under this Section without WGM's prior written consent if the settlement imposes any liability, obligation, admission, or restriction on WGM or any other indemnified party.",
      ],
    },
    {
      id: "warranties",
      title: "16. Disclaimer of Warranties",
      body: [
        "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATIONS ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS.",
        "WGM AND ITS AFFILIATES, LICENSORS, SERVICE PROVIDERS, AND BUSINESS PARTNERS DISCLAIM ALL WARRANTIES, REPRESENTATIONS, GUARANTEES, AND CONDITIONS, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, TO THE EXTENT PERMITTED BY LAW.",
        "WITHOUT LIMITING THE FOREGOING, WE DO NOT WARRANT THAT:",
        {
          clauses: [
            "(a) THE APPLICATIONS WILL MEET YOUR SPECIFIC REQUIREMENTS;",
            "(b) YOUR USE OF THE APPLICATIONS WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE;",
            "(c) INFORMATION OR CONTENT OBTAINED THROUGH THE APPLICATIONS WILL BE ACCURATE, COMPLETE, OR RELIABLE;",
            "(d) OUTPUTS WILL BE ACCURATE, FACTUAL, COMPLETE, ORIGINAL, UNIQUE, NON-INFRINGING, LEGAL, APPROPRIATE, OR SUITABLE FOR YOUR INTENDED PURPOSE;",
            "(e) ANY OUTPUT WILL QUALIFY FOR COPYRIGHT, TRADEMARK, PATENT, OR OTHER INTELLECTUAL PROPERTY PROTECTION;",
            "(f) ANY PARTICULAR AI MODEL, MODEL VERSION, PROVIDER, FEATURE, INTEGRATION, OR FUNCTIONALITY WILL REMAIN AVAILABLE;",
            "(g) THIRD-PARTY AI PROVIDERS OR OTHER THIRD-PARTY SERVICES WILL OPERATE WITHOUT INTERRUPTION, DELAY, ERROR, CAPACITY LIMITATION, OR CHANGE; OR",
            "(h) DEFECTS OR ERRORS WILL BE CORRECTED.",
          ],
        },
        "YOU ACKNOWLEDGE THAT OUTPUTS MAY CONTAIN ERRORS, INACCURACIES, OFFENSIVE CONTENT, OR MATERIAL THAT MAY RESEMBLE THIRD-PARTY CONTENT, AND THAT YOU ARE RESPONSIBLE FOR REVIEWING AND EVALUATING OUTPUTS BEFORE USING THEM.",
      ],
    },
    {
      id: "liability",
      title: "17. Limitation of Liability",
      body: [
        "NOTHING IN THESE TERMS EXCLUDES OR LIMITS LIABILITY THAT CANNOT LAWFULLY BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW, INCLUDING, WHERE APPLICABLE, LIABILITY FOR DEATH OR PERSONAL INJURY CAUSED BY THE NEGLIGENCE OF WGM OR ITS EMPLOYEES, AGENTS, OR SUBCONTRACTORS, OR FOR FRAUD OR FRAUDULENT MISREPRESENTATION.",
        "SUBJECT TO THE FOREGOING, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WGM AND ITS AFFILIATES, LICENSORS, SERVICE PROVIDERS, BUSINESS PARTNERS, THIRD-PARTY AI PROVIDERS, UNDERLYING TECHNOLOGY PROVIDERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND REPRESENTATIVES (COLLECTIVELY, THE “WGM PARTIES”) WILL NOT BE LIABLE FOR ANY:",
        {
          clauses: [
            "(a) DIRECT OR INDIRECT LOSS OF PROFITS OR REVENUE;",
            "(b) LOSS OF GOODWILL;",
            "(c) LOSS OF BUSINESS OR OPPORTUNITY;",
            "(d) LOSS, CORRUPTION, OR UNAVAILABILITY OF DATA OR CONTENT;",
            "(e) INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES; OR",
            "(f) LOSS OR DAMAGE RESULTING FROM:",
            "(i) RELIANCE UPON THE COMPLETENESS, ACCURACY, OR EXISTENCE OF ADVERTISING, OR ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY ADVERTISER OR SPONSOR IN CONNECTION WITH THE APPLICATIONS;",
            "(ii) CHANGES TO THE APPLICATIONS OR PERMANENT OR TEMPORARY CESSATION OF ANY PORTION OF THE APPLICATIONS;",
            "(iii) DELETION, CORRUPTION, LOSS, OR FAILURE TO STORE USER CONTENT, COMMUNICATIONS, OR OTHER DATA MAINTAINED OR TRANSMITTED BY OR THROUGH YOUR USE OF THE APPLICATIONS;",
            "(iv) OUTPUTS OR YOUR RELIANCE UPON, PUBLICATION OF, DISTRIBUTION OF, OR USE OF OUTPUTS;",
            "(v) THE ACTS, OMISSIONS, AVAILABILITY, PERFORMANCE, POLICIES, OR TECHNOLOGY OF THIRD-PARTY AI PROVIDERS OR OTHER THIRD-PARTY SERVICES;",
            "(vi) THE REMOVAL, REPLACEMENT, MODIFICATION, OR DISCONTINUATION OF ANY AI MODEL, MODEL VERSION, FEATURE, INTEGRATION, OR PROVIDER;",
            "(vii) UNAUTHORIZED ACCESS TO YOUR ACCOUNT RESULTING FROM YOUR FAILURE TO MAINTAIN REASONABLE SECURITY OVER YOUR CREDENTIALS; OR",
            "(viii) DECISIONS MADE BASED UPON INFORMATION OR OUTPUTS PROVIDED THROUGH THE APPLICATIONS.",
          ],
        },
        "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE TOTAL AGGREGATE LIABILITY OF THE WGM PARTIES FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE APPLICATIONS OR THESE TERMS WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO WGM FOR THE APPLICATIONS DURING THE SIX (6) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM OR (B) ONE HUNDRED U.S. DOLLARS (US $100).",
        "THE LIMITATIONS IN THIS SECTION APPLY REGARDLESS OF THE THEORY OF LIABILITY AND EVEN IF WGM OR ANY OTHER WGM PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, EXCEPT WHERE SUCH LIMITATION IS PROHIBITED BY APPLICABLE LAW.",
      ],
    },
    {
      id: "termination",
      title: "18. Suspension and Termination",
      body: [
        { h: "18.1 Suspension or Restriction" },
        "WGM may suspend, restrict, limit, or disable your access to some or all of the Applications where we reasonably believe:",
        {
          clauses: [
            "(a) you have violated these Terms;",
            "(b) your account has been compromised or used fraudulently;",
            "(c) your activity presents a security, legal, regulatory, financial, or safety risk;",
            "(d) suspension is necessary to comply with applicable law, legal process, or a Third-Party Service requirement; or",
            "(e) suspension is reasonably necessary to protect WGM, the Applications, another user, or a third party.",
          ],
        },
        { h: "18.2 Termination by WGM" },
        "Subject to applicable law, WGM may terminate your account or access to the Applications if you do not meet the eligibility requirements in Section 3, or for material or repeated violations of these Terms, fraud, abuse, unlawful conduct, security risks, or other grounds described in these Terms. Where practicable and appropriate, WGM may provide notice or an opportunity to cure before termination, but is not required to do so where immediate action is reasonably necessary.",
        "WGM may also discontinue an Application or terminate access without cause upon reasonable notice where appropriate, subject to applicable law and any rights concerning purchased Credits or other prepaid services.",
        { h: "18.3 Termination by You" },
        "You may stop using the Applications at any time and may request deletion of your account using the functionality we provide or by contacting support@pixydust.com, subject to applicable retention requirements.",
        { h: "18.4 Effect of Termination" },
        "Termination does not relieve you of obligations incurred before termination. Except where required by applicable law or expressly provided in the applicable purchase terms, voluntary termination, account deletion, or cessation of use of the Applications does not entitle you to a refund for subscription fees, unused Credits, Add-On Credits, or other amounts previously paid.",
        "If you voluntarily delete your account, any unused Credits associated with that account will no longer be available for use and may be cancelled upon deletion, without refund except where required by applicable law.",
        "Where an account is terminated for fraud, abuse, chargeback activity, or material violation of these Terms, unused Credits may be cancelled or forfeited to the extent permitted by applicable law.",
      ],
    },
    {
      id: "international",
      title: "19. International Users and Consumer Rights",
      body: [
        "The Applications are operated by WGM from the United States and may be accessible from other jurisdictions. You are responsible for determining whether your access to and use of the Applications is lawful in your jurisdiction and for complying with applicable local laws. Nothing in these Terms excludes, restricts, or modifies any consumer guarantee, statutory right, remedy, or other protection that applicable law does not permit the parties to exclude, restrict, or modify. If the laws of your jurisdiction provide mandatory cancellation, withdrawal, refund, warranty, or other consumer rights, those rights will apply notwithstanding conflicting provisions of these Terms.",
        { h: "19.1 EEA/UK Right of Withdrawal" },
        "If you are a consumer resident in the European Economic Area or the United Kingdom, you may have the right to withdraw from your purchase of Credits or other paid digital products, without giving any reason, within fourteen (14) days after the date the applicable contract is concluded, subject to applicable law.",
        "To exercise any applicable right of withdrawal, you must inform WGM of your decision before the applicable withdrawal period expires by a clear statement sent to support@pixydust.com.",
        "If you validly exercise a right of withdrawal, WGM will provide any reimbursement required by applicable law within the time and using the payment method required by applicable law.",
        "Where applicable law provides a withdrawal period, you may request that WGM begin supplying the applicable digital content before the withdrawal period expires. Where permitted by applicable law, if you have expressly consented to immediate supply and acknowledged that beginning supply will result in the loss of your right of withdrawal, your right of withdrawal with respect to digital content will be lost once WGM begins supplying the applicable digital content. WGM will provide any confirmation required by applicable law.",
        "Where you have made the applicable request and provided any consent or acknowledgment required by applicable law:",
        {
          clauses: [
            "(a) to the extent permitted by applicable law, for digital content not supplied on a tangible medium, which may include generated Outputs or other digital content supplied through the Applications, you will lose your right of withdrawal once WGM begins supplying the applicable digital content. Use of any portion of Credits obtained as part of a single purchase or Credit allocation will result in the loss of any applicable right of withdrawal with respect to that entire purchase or allocation, including any unused Credits remaining from that purchase or allocation; and",
            "(b) for services, if you expressly request that performance begin during the withdrawal period and subsequently exercise a valid right of withdrawal before performance is complete, you may be required to pay an amount proportionate to the services provided before you informed WGM of your decision to withdraw, to the extent permitted by applicable law.",
          ],
        },
        "For purposes of determining when performance, supply, or use has begun, use of Credits to initiate a generation, processing request, or other Credit-based functionality constitutes use of the applicable Credits and may constitute the beginning of performance. Supply of digital content may begin when WGM begins providing or making available the applicable generated Output or other digital content. Merely logging into, browsing, or viewing the Applications without using Credits does not, by itself, constitute use of Credits or supply of paid digital content. Nothing in these Terms limits or excludes any mandatory consumer right or remedy available to you under applicable law that cannot lawfully be limited, excluded, or waived.",
      ],
    },
    {
      id: "arbitration",
      title: "20. Arbitration, Class-Action Waiver, and Jury Waiver",
      body: [
        "PLEASE READ THIS SECTION CAREFULLY BECAUSE IT PROVIDES THAT YOU AGREE TO RESOLVE CERTAIN DISPUTES THROUGH BINDING INDIVIDUAL ARBITRATION AND INCLUDES A CLASS ACTION WAIVER AND JURY TRIAL WAIVER.",
        "This Arbitration Agreement supersedes prior versions to the extent permitted by applicable law and extends to WGM and the WGM Parties.",
        { h: "20.1 Applicability of Arbitration Agreement" },
        "You and the WGM Parties agree that all claims and disputes, whether based in contract, tort, statute, or otherwise, arising out of or relating to these Terms, use of the Applications, or communications between you and the WGM Parties that are not brought in small claims court will be resolved by binding arbitration on an individual basis, except that you and the WGM Parties are not required to arbitrate:",
        {
          clauses: [
            "(a) disputes or claims within the jurisdiction of a small claims court consistent with applicable jurisdictional and dollar limits, provided the matter proceeds individually and not as a class action;",
            "(b) disputes or claims where the only relief sought is injunctive relief; or",
            "(c) disputes in which either party seeks equitable relief for alleged unlawful use of copyrights, trademarks, trade names, logos, trade secrets, patents, or other intellectual property rights.",
          ],
        },
        "To the extent permitted by applicable law, “all claims and disputes” includes claims and disputes that arose between the parties before the applicable version of these Terms became effective.",
        "Disputes concerning arbitrability, including the scope, applicability, enforceability, revocability, or validity of this Arbitration Agreement, will be determined by the arbitrator except as expressly provided in this Section.",
        { h: "20.2 Informal Dispute Resolution First" },
        "Before initiating arbitration, the party asserting a dispute must provide an individualized written pre-arbitration demand (“Pre-Arbitration Demand”).",
        "A Pre-Arbitration Demand to WGM must be sent to: arbitration@pixydust.com",
        "A Pre-Arbitration Demand must relate to and be submitted on behalf of a single individual. A Pre-Arbitration Demand submitted on behalf of multiple individuals will not satisfy this Section with respect to any such individual. The Pre-Arbitration Demand must include the individual's name, applicable username or account information, telephone number, email address, mailing address, a description of the dispute and requested relief, and the individual's signature.",
        "If represented by counsel, applicable counsel contact information should also be included. If the WGM Parties have a dispute with you, the WGM Parties may send their individualized Pre-Arbitration Demand, including the applicable information required above, to the email address, phone number, or other contact information associated with your account. If the dispute is not resolved within sixty (60) days after a valid Pre-Arbitration Demand is sent, arbitration may then be filed.",
        "Compliance with this informal dispute-resolution procedure is a condition precedent to commencing arbitration to the extent permitted by applicable law. To the extent permitted by applicable law, the arbitrator shall dismiss any arbitration filed without compliance with this informal dispute-resolution procedure. Nothing in this Section prevents a party from seeking a judicial determination regarding whether the requirements of this Section 20.2 have been satisfied where such judicial determination is permitted by applicable law.",
        { h: "20.3 Arbitration Rules" },
        "The Federal Arbitration Act, including its procedural provisions, governs the interpretation and enforcement of this Arbitration Agreement, and not state arbitration law.",
        "Arbitration will be administered by ADR Services, Inc. (“ADR Services”) under its applicable arbitration rules then in effect. If ADR Services declines or is unable to administer the arbitration, the arbitration will be administered by National Arbitration and Mediation (“NAM”) under its applicable arbitration rules then in effect. The applicable arbitration rules will govern all aspects of the arbitration except to the extent they conflict with these Terms or applicable law. The arbitration will be conducted by one neutral arbitrator.",
        "Any claim or dispute where the total amount sought is less than $10,000 USD may be resolved through binding non-appearance arbitration, at the option of the party seeking relief, subject to applicable law. For claims or disputes where the total amount sought is $10,000 USD or more, the right to a hearing will be determined by the applicable arbitration rules. Any judgment upon an arbitration award may be entered in a court of competent jurisdiction.",
        { h: "20.4 Non-Appearance Arbitration" },
        "If non-appearance arbitration is elected, the arbitration will be conducted by telephone, videoconference, online proceedings, written submissions, or any combination of those methods, and the specific manner will be chosen by the party initiating the arbitration, subject to applicable law. No personal appearance by the parties or witnesses will be required unless mutually agreed by the parties or required by applicable law.",
        { h: "20.5 Fees" },
        "Responsibility for arbitration filing fees, administrative fees, arbitrator compensation, and other arbitration costs will be determined by the applicable arbitration rules and applicable law. If WGM initiates arbitration against you, WGM will pay arbitration costs to the extent required by the applicable arbitration rules or applicable law. Nothing in this Section requires you to pay fees or costs that applicable law or the applicable arbitration rules prohibit WGM from imposing upon you.",
        "To the extent permitted by the applicable arbitration rules and applicable law, WGM may seek, and the arbitrator may award, reallocation or reimbursement of arbitration filing fees, administrative fees, arbitrator compensation, and other arbitration costs where a claim or counterclaim is determined to have been filed for purposes of harassment, to be frivolous, or otherwise to satisfy the applicable standard for reallocation or reimbursement.",
        "Except as otherwise provided by applicable law or the applicable arbitration rules, each party will bear its own attorneys’ fees and expenses incurred in arbitration. Notwithstanding the foregoing, the arbitrator may award attorneys’ fees and expenses if the arbitrator determines that a claim, defense, or relief sought was frivolous or brought for an improper purpose, to the extent permitted by applicable law.",
        "If either party must seek a court order to compel arbitration, the party that obtains such order may recover its reasonable attorneys’ fees and expenses from the other party, to the extent permitted by applicable law.",
        "The prevailing party in any court action concerning satisfaction of a condition precedent to arbitration may recover its reasonable attorneys’ fees and expenses, to the extent permitted by applicable law.",
        { h: "20.6 Authority of the Arbitrator" },
        "The arbitrator will determine the rights and liabilities of you and the WGM Parties and, except where a determination is expressly reserved for a court under this Arbitration Agreement or applicable law, will determine matters within the arbitrator's jurisdiction.",
        "The dispute will not be consolidated with other matters or joined with claims involving other parties except where expressly permitted by this Arbitration Agreement, required by applicable law, or agreed by the parties. The arbitrator will have authority to grant motions dispositive of all or part of any claim or dispute and to grant monetary and non-monetary relief available to an individual under applicable law, the applicable arbitration rules, and these Terms.",
        "The arbitrator will issue a written award consistent with the applicable arbitration rules, including the essential findings and conclusions upon which the award is based where required or permitted by those rules, and any calculation of damages awarded where applicable.",
        "The arbitrator will have the same authority to award relief on an individual basis that a judge in a court of law would have, subject to this Arbitration Agreement, the applicable arbitration rules, and applicable law. The award will be final and binding, subject to any review permitted by applicable law.",
        { h: "20.7 Settlement Offers" },
        "To the extent permitted by applicable law and the applicable arbitration rules, at least ten (10) calendar days before the date set for the arbitration hearing, either party may serve a written offer of judgment on the other party to allow judgment on specified terms.",
        "If the offer is accepted, the offer and proof of acceptance may be submitted to the arbitration provider for entry in accordance with the applicable arbitration rules.",
        "If the offer is not accepted before the arbitration hearing or within thirty (30) calendar days after it is made, whichever occurs first, the offer will be deemed withdrawn and may not be introduced as evidence in the arbitration except to the extent necessary to determine costs or fees after the arbitrator has determined the merits. If an offer made by one party is not accepted by the other party and the other party fails to obtain an award more favorable than the offer, then, to the extent permitted by applicable law and the applicable arbitration rules, the other party will not recover its post-offer costs and will be responsible for the offering party's recoverable post-offer costs, including fees paid to the arbitration provider, from the date of the offer.",
        { h: "20.8 Waiver of Jury Trial" },
        "YOU AND THE WGM PARTIES WAIVE, TO THE FULLEST EXTENT PERMITTED BY LAW, ANY CONSTITUTIONAL OR STATUTORY RIGHT TO HAVE CLAIMS SUBJECT TO THIS ARBITRATION AGREEMENT DECIDED IN COURT BY A JUDGE OR JURY.",
        "You and the WGM Parties instead agree to have claims and disputes subject to this Arbitration Agreement resolved through arbitration. Arbitration differs from litigation in court and is generally subject to more limited judicial review. Where litigation concerning enforcement or vacation of an arbitration award is permitted, you and the WGM Parties waive the right to a jury trial to the fullest extent permitted by law.",
        { h: "20.9 Waiver of Class, Collective, Consolidated, or Representative Actions" },
        "ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS, COLLECTIVE, CONSOLIDATED, PRIVATE ATTORNEY GENERAL, OR REPRESENTATIVE BASIS, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.",
        "Claims of more than one user or customer may not be arbitrated or litigated jointly or consolidated except where applicable law requires otherwise or the parties expressly agree.",
        "For clarity, the administration of multiple individual arbitration demands under any applicable mass-arbitration or coordinated-filing procedures of the arbitration provider will not, by itself, constitute or authorize joint, consolidated, class, collective, private attorney general, or representative arbitration of the merits. Each claim will remain an individual claim unless the parties expressly agree otherwise or applicable law requires otherwise.",
        "For clarity, the administration of multiple individual arbitration demands under any applicable mass-arbitration or coordinated-filing procedures of the arbitration provider will not, by itself, constitute or authorize joint, consolidated, class, collective, private attorney general, or representative arbitration of the merits. Each claim will remain an individual claim unless the parties expressly agree otherwise or applicable law requires otherwise.",
        "This provision does not prevent participation in a class-wide settlement.",
        "Notwithstanding any other provision of these Terms, this Arbitration Agreement, or the applicable arbitration rules, disputes concerning the interpretation, applicability, or enforceability of this class, collective, consolidated, private attorney general, or representative action waiver will be determined by a court where required by applicable law.",
        "If this waiver is limited, voided, or found unenforceable as to a particular proceeding, and that determination permits the proceeding to continue on a class, collective, consolidated, private attorney general, or representative basis, then the agreement to arbitrate will not apply to that proceeding unless the parties mutually agree otherwise. Any such proceeding that is permitted to continue on a class, collective, consolidated, private attorney general, or representative basis must proceed in a court of competent jurisdiction and not in arbitration.",
        { h: "20.10 Right to Waive" },
        "Any right or limitation under this Arbitration Agreement may be waived by the party against whom the claim is asserted with respect to a particular claim. Such waiver does not waive or affect any other portion of this Arbitration Agreement.",
        { h: "20.11 Small Claims Court" },
        "Notwithstanding the foregoing, either you or the WGM Parties may bring an individual action in small claims court where the dispute qualifies.",
        { h: "20.12 Arbitration Agreement Survival" },
        "This Arbitration Agreement survives termination of your relationship with WGM or the WGM Parties, including termination or deletion of your account, revocation of consent, or other action by you to end your participation in or use of the Applications or communications with the WGM Parties.",
      ],
    },
    {
      id: "other",
      title: "21. Other Terms",
      body: [
        { h: "21.1 Entire Agreement" },
        "These Terms and any supplemental terms applicable to your use of the Applications constitute the complete agreement between you and WGM concerning the Applications and supersede prior agreements concerning the same subject matter, except as otherwise expressly provided.",
        { h: "21.2 Choice of Law" },
        "Except to the extent overridden by U.S. federal law or mandatory applicable law, these Terms and claims or disputes arising out of or relating to these Terms or their subject matter are governed by the laws of the State of New York, without regard to its conflict-of-laws principles.",
        { h: "21.3 Exclusive Venue" },
        "For disputes or proceedings that are not subject to arbitration, are not eligible for small claims court, or otherwise may properly be brought before a court in connection with the Arbitration Agreement or an arbitration award, and except where applicable law requires otherwise, you and WGM consent to exclusive jurisdiction and venue in the United States District Court for the Southern District of New York, where federal subject-matter jurisdiction exists, or the Supreme Court of the State of New York, New York County, as applicable.",
        { h: "21.4 No Waiver" },
        "WGM's failure to enforce any provision of these Terms does not constitute a waiver of that provision or any other right.",
        { h: "21.5 Severability" },
        "If any provision of these Terms is determined to be invalid, illegal, or unenforceable, that provision will be enforced to the maximum extent permitted by law or severed to the minimum extent necessary, and the remaining provisions will remain in full force and effect.",
        { h: "21.6 Assignment" },
        "You may not assign or transfer these Terms or any rights or obligations under them without WGM's prior written consent.",
        "WGM may assign or transfer these Terms or any of its rights or obligations under them, in whole or in part, and may provide or arrange for the provision of the Applications through another entity, including in connection with a merger, acquisition, corporate reorganization, financing, sale of assets, or transfer of the Applications or relevant business, subject to applicable law.",
        { h: "21.7 Force Majeure" },
        "WGM will not be responsible for delay, interruption, failure, or inability to perform resulting from circumstances beyond its reasonable control, including natural disasters, acts of government, war, terrorism, civil unrest, labor disputes, internet or telecommunications failures, power outages, cyberattacks, cloud or infrastructure failures, or failures, restrictions, outages, policy changes, or discontinuation by Third-Party AI Providers, APIs, hosting providers, payment providers, or other third-party services.",
        { h: "21.8 Electronic Communications and Notices" },
        "You consent to receive notices and communications relating to the Applications and these Terms electronically, including through the Applications, by email, or through other contact information associated with your account, to the extent permitted by applicable law.",
        "You are responsible for maintaining accurate contact information associated with your account.",
        "Legal notices to WGM should be sent to: legal@pixydust.com",
        { h: "21.9 Relationship of the Parties" },
        "Nothing in these Terms creates a partnership, joint venture, employment, agency, fiduciary, franchise, or other similar relationship between you and WGM.",
        { h: "21.10 Headings" },
        "Section titles and headings are provided for convenience and do not affect interpretation of these Terms.",
        { h: "21.11 Survival" },
        "Any provisions that by their nature should survive termination of these Terms, termination or deletion of your account, or cessation of your use of the Applications will survive, including provisions concerning ownership, licenses intended to survive, indemnification, warranty disclaimers, limitations of liability, dispute resolution, and accrued rights and obligations.",
        { h: "21.12 Supplemental Terms" },
        "Certain Applications, AI models, features, promotions, products, enterprise offerings, or other services may be subject to additional terms presented to you in connection with those offerings.",
        "If supplemental terms conflict with these Terms, the supplemental terms will control with respect to the specific feature, product, or service to which they apply, unless expressly stated otherwise.",
        { h: "21.13 California Consumer Rights Notice" },
        "If you are a California resident, in accordance with California Civil Code § 1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting them in writing at 1625 North Market Blvd., Suite N 112, Sacramento, CA 95834, or by telephone at (800) 952-5210.",
        { h: "21.14 Contact Us" },
        "Questions regarding these Terms or the Applications may be directed to: support@pixydust.com",
        "WGM reserves all rights not expressly granted under these Terms.",
      ],
    },
  ],
};
