-- Migration 0016: five NYC .5 iPhone photoshoot presets for /shoots.
-- Cool daytime digital-flash vibe. Idempotent upserts.

INSERT INTO templates (
  id, title, kind, type, category, provider, model,
  input_json, fields_json, credit_cost, quality_json, aspects_json, quantities_json,
  eta, tags_json, tone, accent, subtitle, description, preview_image, meta,
  is_featured, is_hidden, is_admin_only, is_adult, sort_order, updated_at
) VALUES
(
  'nyc-dot5-stairwell',
  'NYC Stairwell .5',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a portrait of her as a cool-vibe .5 iPhone photo of me — selfie angle in a NYC apartment building stairwell, daytime. Ultra-wide front-camera perspective, arm slightly extended holding the phone, concrete steps and metal handrail behind, painted stairwell walls, soft window light from landings mixed with harsh digital flash on the face, candid cool energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best for selfie angle"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["nyc",".5","selfie","stairwell","flash","street"]', 'noir', 'var(--pd-lilac)',
  'Selfie · stairwell · digital flash',
  'A cool .5 stairwell selfie in a NYC building — concrete steps, metal rail, daytime digital flash.',
  NULL,
  '{"kicker":"Photoshoot · NYC .5 Selfie","howItWorks":["Upload 1–4 clear photos of yourself","We place you in a NYC building stairwell selfie","Pick an aspect ratio and generate"]}',
  1, 0, 0, 0, 10, datetime('now')
),
(
  'nyc-dot5-subway',
  'NYC Subway Seat .5',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a portrait of her as a cool-vibe .5 iPhone photo of me — selfie angle sitting on a crowded NYC subway seat, daytime underground car lighting. Ultra-wide front-camera selfie, arm extended, other passengers blurred beside and across the aisle, orange/yellow subway seats, metal poles and ads in the background, fluorescent train light mixed with digital flash on the face, candid cool commute energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face shots look best in the crowded car"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["nyc",".5","selfie","subway","train","flash"]', 'dusk', 'var(--pd-amber)',
  'Selfie · crowded car · flash',
  'Packed NYC subway seat selfie — orange seats, poles, strangers, cool .5 digital flash.',
  NULL,
  '{"kicker":"Photoshoot · NYC .5 Selfie","howItWorks":["Upload clear photos of yourself","We drop you onto a crowded subway seat selfie","Generate the commute still"]}',
  1, 0, 0, 0, 11, datetime('now')
),
(
  'nyc-dot5-cafe',
  'NYC Cafe Coffee .5',
  'shoot', 'image', 'Lifestyle', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a portrait of her as a cool-vibe .5 iPhone photo of me — selfie angle in a NYC cafe holding a coffee, daytime. Ultra-wide front-camera selfie, arm extended, paper coffee cup in the other hand near the lens, marble or wood cafe table edge, large windows with blurred city street behind, soft daylight mixed with digital flash on the face, iced or hot coffee visible, candid cool cafe energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Face-forward photos work great with the coffee cup in frame"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["nyc",".5","selfie","cafe","coffee","flash"]', 'mint', 'var(--pd-mint)',
  'Selfie · coffee in hand · cafe',
  'NYC cafe .5 selfie holding coffee — window light, cup in frame, cool daytime flash.',
  NULL,
  '{"kicker":"Photoshoot · NYC .5 Selfie","howItWorks":["Upload your photos","We place you in a NYC cafe selfie with coffee","Pick ratio and generate"]}',
  1, 0, 0, 0, 12, datetime('now')
),
(
  'nyc-dot5-bodega',
  'NYC Bodega Street .5',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a portrait of her as a cool-vibe .5 iPhone photo of me walking in New York City, daytime — fashion street shot outside a classic NYC bodega. Ultra-wide .5 rear-camera street photo, full or three-quarter body, standing on the sidewalk in front of a corner bodega with awning, stacked produce crates, neon beer signs in the window, fire escape above, digital flash firing in daylight for that harsh cool snapshot look, candid fashion energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone photography, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Full-body or three-quarter shots help for street fashion framing"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["nyc",".5","bodega","street","fashion","flash"]', 'teal', 'var(--pd-teal)',
  'Street · bodega · daytime flash',
  'Fashion .5 street still outside a NYC bodega — awning, crates, daylight digital flash.',
  NULL,
  '{"kicker":"Photoshoot · NYC .5 Street","howItWorks":["Upload photos of yourself","We shoot you outside a classic NYC bodega","Generate the street fashion still"]}',
  1, 0, 0, 0, 13, datetime('now')
),
(
  'nyc-dot5-walk',
  'NYC Walk .5',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone photo of me{{look}} walking in New York City, daytime. Fashion street shot mid-stride on a busy NYC sidewalk, ultra-wide .5 rear-camera perspective, yellow cabs and brownstones or glass towers softly blurred behind, crosswalk stripes optional, digital flash firing in daylight for that harsh cool snapshot look, wind in hair, candid walking energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone photography, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Full-body walking shots or clear face + outfit photos work best"},{"key":"look","type":"select","label":"Outfit","required":true,"default":" ","help":"Keep the clothes in your photo, or switch into our NYC street look (male / female).","options":[{"value":" ","label":"Keep my original outfit"},{"value":", wearing a cropped asymmetrical one-shoulder tight black top, baggy black jeans, chrome glasses, and a black leather belt with a chrome D-ring buckle. Match the outfit reference image closely","label":"Female — one-shoulder top + baggy jeans","image":"https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785102889634.png","ref":"https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785102889634.png"},{"value":", wearing a loose black tank top, baggy black jeans, chrome glasses, and a black leather belt with a chrome D-ring buckle. Match the outfit reference image closely","label":"Male — loose tank + baggy jeans","image":"https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785102892530.png","ref":"https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785102892530.png"}]}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["nyc",".5","walk","street","fashion","flash"]', 'ice', 'var(--pd-mint)',
  'Street walk · keep or change outfit',
  'Cool .5 NYC daytime walk with digital flash — keep your outfit, or switch into our black street look (female or male).',
  NULL,
  '{"kicker":"Photoshoot · NYC .5 Street","howItWorks":["Upload photos of yourself","Keep your outfit or pick the female / male street look","We put you mid-stride on a NYC sidewalk"]}',
  1, 0, 0, 0, 14, datetime('now')
)
ON CONFLICT(id) DO UPDATE SET
  title=excluded.title,
  kind=excluded.kind,
  type=excluded.type,
  category=excluded.category,
  provider=excluded.provider,
  model=excluded.model,
  input_json=excluded.input_json,
  fields_json=excluded.fields_json,
  credit_cost=excluded.credit_cost,
  quality_json=excluded.quality_json,
  aspects_json=excluded.aspects_json,
  quantities_json=excluded.quantities_json,
  eta=excluded.eta,
  tags_json=excluded.tags_json,
  tone=excluded.tone,
  accent=excluded.accent,
  subtitle=excluded.subtitle,
  description=excluded.description,
  preview_image=COALESCE(excluded.preview_image, templates.preview_image),
  meta=excluded.meta,
  is_featured=excluded.is_featured,
  is_hidden=excluded.is_hidden,
  is_admin_only=excluded.is_admin_only,
  sort_order=excluded.sort_order,
  updated_at=datetime('now');
