-- Migration 0018: NYC Stairwell .5 — keep original outfit OR male/female street look.

UPDATE templates SET
  input_json = '{"prompt":"Generate a cool-vibe .5 iPhone photo of me{{look}} — selfie .5 wide angle in a NYC apartment building stairwell, metal stairs, white walls, industrial, fluorescent lighting, daytime. Ultra-wide front-camera perspective, arm slightly extended holding the phone, concrete steps and metal handrail behind, painted stairwell walls, soft window light from landings mixed with harsh digital flash on the face, candid cool energy, sharp facial likeness to the reference photos, natural skin texture, beautiful retouched skin, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  fields_json = '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best for selfie angle"},{"key":"look","type":"select","label":"Outfit","required":true,"default":" ","help":"Keep the clothes in your photo, or switch into our stairwell street look (male / female).","options":[{"value":" ","label":"Keep my original outfit"},{"value":", wearing a fitted black leather halter tank top, black baggy cargo jeans, platform sneakers, a black belt with metal spikes and a chrome D-shaped buckle, a chrome emo jewelry chain choker, chrome chain bracelet, chrome nails, and chrome Oakley sunglasses. Hair styled. Match the outfit reference image closely","label":"Female — leather halter + cargo jeans","image":"https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785103834026.png","ref":"https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785103834026.png"},{"value":", wearing a black t-shirt tucked into baggy dress pants, a black belt, Oakley sunglasses, chrome bracelets, with styled hair. Match the outfit reference image closely","label":"Male — tucked tee + dress pants","image":"https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785103839129.png","ref":"https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785103839129.png"}]}]',
  subtitle = 'Stairwell selfie · keep or change outfit',
  description = 'Cool .5 NYC stairwell selfie with digital flash — keep your outfit, or switch into our male / female street look.',
  meta = '{"kicker":"Photoshoot · NYC .5 Selfie","howItWorks":["Upload 1–4 clear photos of yourself","Keep your outfit or pick the female / male stairwell look","We place you in a NYC building stairwell selfie"]}',
  updated_at = datetime('now')
WHERE id = 'nyc-dot5-stairwell';
