-- 20 camera-style presets: angle, lens, lighting, and color grading only.
-- Do not change face structure, outfit, or pose.

INSERT INTO templates (
  id, title, kind, type, category, provider, model,
  input_json, fields_json, credit_cost, quality_json, aspects_json, quantities_json,
  eta, tags_json, tone, accent, subtitle, description, preview_image, meta,
  is_featured, is_hidden, is_admin_only, is_adult, sort_order, updated_at
) VALUES
(
  'preset-y2k-digicam-flash',
  'Y2K Digicam Flash',
  'preset', 'image', 'Y2K', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo as an early-2000s Y2K digicam snapshot with on-camera flash — slightly overexposed flash pop, cool blue LCD whites, mild jpeg compression, tiny sensor noise, candid party energy. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change camera style, lighting, and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["y2k","digicam","flash","camera","grade"]', 'pink', 'var(--pd-pink)',
  'Y2K · digicam flash',
  'Early-2000s digicam flash look — jpeg crunch, cool whites. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165220152.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 10, datetime('now')
),
(
  'preset-y2k-cyber-chrome',
  'Y2K Cyber Chrome',
  'preset', 'image', 'Y2K', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo with a Y2K cyber chrome grade — icy cyan highlights, silver-blue midtones, subtle holographic sheen in speculars, clean futuristic early-2000s magazine color. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lighting and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["y2k","chrome","cyan","grade","camera"]', 'ice', 'var(--pd-mint)',
  'Y2K · cyber chrome grade',
  'Icy cyan-silver Y2K chrome grade. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165224093.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 11, datetime('now')
),
(
  'preset-y2k-pink-webcam',
  'Y2K Pink Webcam',
  'preset', 'image', 'Y2K', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo as a soft early-2000s webcam / MSN-era still — gentle pink-magenta cast, soft focus, mild vignette, low-res webcam softness, nostalgic bedroom-internet glow. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change camera style, lighting, and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["y2k","webcam","pink","soft","grade"]', 'dusk', 'var(--pd-lilac)',
  'Y2K · pink webcam',
  'Soft pink webcam nostalgia. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165223977.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 12, datetime('now')
),
(
  'preset-night-party-flash',
  'Night Party Flash',
  'preset', 'image', 'Cameras', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo as a dark night party flash photo — harsh direct on-camera flash, deep black shadows behind the subject, bright specular highlights on skin, candid nightlife snapshot energy. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change camera style, lighting, and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["night","flash","party","camera","lighting"]', 'noir', 'var(--pd-lilac)',
  'Night · party flash',
  'Harsh night flash, crushed blacks. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165228142.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 13, datetime('now')
),
(
  'preset-dark-alley-flash',
  'Dark Alley Flash',
  'preset', 'image', 'Mood', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo as a dark night flash still with moody alley energy — single harsh flash, long falloff into darkness, cool shadows, slight grain, cinematic night snapshot. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change camera style, lighting, and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["night","flash","noir","mood","lighting"]', 'noir', 'var(--pd-amber)',
  'Night · dark flash',
  'Moody dark flash with long falloff. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165276118.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 14, datetime('now')
),
(
  'preset-golden-hour-sky',
  'Golden Hour Sky',
  'preset', 'image', 'Mood', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo with stunning golden-hour sunset lighting — warm amber key light wrapping the subject, glowing orange-pink sky influence, soft long shadows, dreamy late-day atmosphere. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lighting and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["sunset","golden","hour","lighting","mood"]', 'amber', 'var(--pd-amber)',
  'Sunset · golden hour',
  'Warm amber sunset wrap light. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165262823.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 15, datetime('now')
),
(
  'preset-magic-hour-flare',
  'Magic Hour Flare',
  'preset', 'image', 'Mood', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo at magic hour with stunning sky light and soft lens flare — peach and rose sunset tones, gentle flare streaks, glowing rim light on hair and shoulders, romantic evening light. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lighting, lens effects, and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["sunset","flare","magic","hour","lighting"]', 'dusk', 'var(--pd-pink)',
  'Sunset · magic hour flare',
  'Peach sunset light with soft flare. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165281610.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 16, datetime('now')
),
(
  'preset-blue-hour-glow',
  'Blue Hour Glow',
  'preset', 'image', 'Mood', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo in blue hour light — deep cobalt and indigo sky tones, soft cool ambient fill, gentle warm window/street practicals if present, serene post-sunset glow. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lighting and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["bluehour","sunset","cool","lighting","mood"]', 'ice', 'var(--pd-teal)',
  'Sunset · blue hour',
  'Deep cobalt post-sunset light. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165282908.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 17, datetime('now')
),
(
  'preset-fisheye-ultra-wide',
  'Fisheye Ultra Wide',
  'preset', 'image', 'Cameras', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo as if shot on an ultra-wide fisheye lens — curved barrel distortion, exaggerated edges, dramatic wide FOV, circular stretch toward frame borders, playful extreme wide look. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lens geometry and camera style. Do not restyle clothes or reshape facial identity.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["fisheye","wide","lens","camera","distortion"]', 'teal', 'var(--pd-teal)',
  'Lens · fisheye',
  'Ultra-wide fisheye barrel distortion. Face identity + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165337267.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 18, datetime('now')
),
(
  'preset-fisheye-peephole',
  'Fisheye Peephole',
  'preset', 'image', 'Cameras', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo with extreme peephole fisheye distortion — strong circular vignette, heavily bowed edges, compressed center, door-viewer / security-peephole look. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lens geometry and framing style. Do not restyle clothes or reshape facial identity.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["fisheye","peephole","lens","camera","wide"]', 'noir', 'var(--pd-lilac)',
  'Lens · peephole fisheye',
  'Extreme circular peephole fisheye. Face identity + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165344107.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 19, datetime('now')
),
(
  'preset-high-angle-down',
  'High Angle Down',
  'preset', 'image', 'Creative', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo from a high camera angle looking down — elevated top-down perspective, subject slightly smaller in frame, ceiling/sky bias if applicable, editorial high-angle composition. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change camera angle and perspective. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["highangle","angle","camera","perspective","creative"]', 'mint', 'var(--pd-mint)',
  'Angle · high looking down',
  'Elevated high-angle perspective. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165338913.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 20, datetime('now')
),
(
  'preset-low-angle-hero',
  'Low Angle Hero',
  'preset', 'image', 'Creative', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo from a low hero camera angle looking up — ground-level upward perspective, taller commanding presence, more sky/ceiling in frame, dramatic low-angle composition. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change camera angle and perspective. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["lowangle","hero","angle","camera","perspective"]', 'teal', 'var(--pd-teal)',
  'Angle · low hero up',
  'Dramatic low-angle hero look. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165338721.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 21, datetime('now')
),
(
  'preset-dutch-tilt',
  'Dutch Tilt',
  'preset', 'image', 'Creative', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo with a stylish dutch tilt — camera rolled diagonally, dynamic off-kilter horizon, editorial canted-angle energy. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change camera angle. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["dutch","tilt","angle","camera","creative"]', 'lilac', 'var(--pd-lilac)',
  'Angle · dutch tilt',
  'Canted dutch-tilt framing. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165400379.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 22, datetime('now')
),
(
  'preset-zoom-out-wide',
  'Zoom Out Wide',
  'preset', 'image', 'Creative', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo as a zoomed-out wider shot — pull the camera back, show more environment around the subject, looser full-scene framing, environmental portrait feel while keeping the subject recognizable. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change framing and focal length feel. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["zoom","wide","framing","camera","creative"]', 'mint', 'var(--pd-mint)',
  'Framing · zoom out',
  'Pull-back wider environmental framing. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165384613.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 23, datetime('now')
),
(
  'preset-selfie-distortion-fix',
  'Selfie Distortion Fix',
  'preset', 'image', 'Cameras', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo to correct typical front-camera selfie distortion — neutralize wide-angle face warp, naturalize nose/forehead proportions, keep a flattering but realistic phone-portrait look without beautifying or reshaping identity. Keep every face identity, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only correct lens distortion and perspective. Do not change makeup style, restyle clothes, or alter who the person is.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Works great on close selfies — identity stays locked"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["selfie","distortion","fix","lens","camera"]', 'ice', 'var(--pd-mint)',
  'Lens · selfie fix',
  'Corrects selfie wide-angle warp. Identity + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165400575.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 24, datetime('now')
),
(
  'preset-portrait-50mm',
  'Portrait 50mm',
  'preset', 'image', 'Cameras', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo as if shot on a classic 50mm portrait lens — natural perspective compression, soft background separation, flattering mid-tele look, clean prime-lens sharpness. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lens feel and shallow depth cues. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["50mm","portrait","lens","camera","prime"]', 'amber', 'var(--pd-amber)',
  'Lens · 50mm portrait',
  'Classic 50mm compression and separation. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165392565.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 25, datetime('now')
),
(
  'preset-anamorphic-flare',
  'Anamorphic Flare',
  'preset', 'image', 'Cameras', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo with cinematic anamorphic lens character — horizontal blue/orange streak flares, oval bokeh feel, widescreen cinema atmosphere, subtle widescreen squeeze vibe without changing composition content. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lens character, flares, and grade. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["anamorphic","flare","cinema","lens","camera"]', 'dusk', 'var(--pd-lilac)',
  'Lens · anamorphic',
  'Cinematic anamorphic streak flares. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165447992.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 26, datetime('now')
),
(
  'preset-teal-orange-cinema',
  'Teal Orange Cinema',
  'preset', 'image', 'Color grades', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo with a cinematic teal-and-orange color grade — cool teal shadows, warm orange skin highlights, blockbuster contrast curve, polished movie still look. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change color grading and contrast. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["teal","orange","cinema","grade","color"]', 'teal', 'var(--pd-teal)',
  'Grade · teal & orange',
  'Blockbuster teal-orange cinema grade. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165447023.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 27, datetime('now')
),
(
  'preset-softbox-beauty-light',
  'Softbox Beauty Light',
  'preset', 'image', 'Color grades', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo with softbox beauty lighting only — large soft key light, gentle wrap, clean catchlights, even flattering illumination, minimal hard shadows, studio beauty-light quality without makeup changes. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change lighting. Do not restyle clothes, add makeup looks, or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["softbox","beauty","lighting","studio","grade"]', 'lilac', 'var(--pd-lilac)',
  'Light · softbox beauty',
  'Large soft beauty key light. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165432101.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 28, datetime('now')
),
(
  'preset-disposable-flash',
  'Disposable Flash',
  'preset', 'image', 'Cameras', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Reprocess this photo as a disposable film camera flash shot — harsh cheap flash, slight greenish-yellow cast, soft focus, heavy grain, party disposable snapshot vibe. Keep every face, face structure, facial features, hair, skin texture, outfit, body pose, and all people exactly the same — only change camera style, lighting, and color grading. Do not restyle clothes or reshape the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Up to 4 photos — face + outfit stay the same"}]',
  5, NULL, '["original","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["disposable","flash","film","camera","grain"]', 'amber', 'var(--pd-amber)',
  'Camera · disposable flash',
  'Grainy disposable flash snapshot. Face + outfit locked.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785165452061.png'"kicker":"Preset · Camera Style","howItWorks":["Upload your photo","We restyle camera, lighting, and grade only","Face and outfit stay the same"]}',
  1, 0, 0, 0, 29, datetime('now')
)
ON CONFLICT(id) DO UPDATE SET
  title=excluded.title,
  kind=excluded.kind,
  type=excluded.type,
  category=excluded.category,
  provider=excluded.provider,
  model=excluded.model,
  input_json=excluded.input_json,
  fields_json=excluded.fields_json,
  credit_cost=excluded.credit_cost,
  quality_json=excluded.quality_json,
  aspects_json=excluded.aspects_json,
  quantities_json=excluded.quantities_json,
  eta=excluded.eta,
  tags_json=excluded.tags_json,
  tone=excluded.tone,
  accent=excluded.accent,
  subtitle=excluded.subtitle,
  description=excluded.description,
  preview_image=COALESCE(excluded.preview_image, templates.preview_image),
  meta=excluded.meta,
  is_featured=excluded.is_featured,
  is_hidden=excluded.is_hidden,
  is_admin_only=excluded.is_admin_only,
  is_adult=excluded.is_adult,
  sort_order=excluded.sort_order,
  updated_at=excluded.updated_at;
