-- Editorial scene recreations (Street / Lifestyle). Face + hair locked from upload; no invented hair color / body type.

INSERT INTO templates (
  id, title, kind, type, category, provider, model,
  input_json, fields_json, credit_cost, quality_json, aspects_json, quantities_json,
  eta, tags_json, tone, accent, subtitle, description, preview_image, meta,
  is_featured, is_hidden, is_admin_only, is_adult, sort_order, updated_at
) VALUES
(
  'street-elevator-fur-flash',
  'Elevator Fur Flash',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Put me from the reference photos into this exact scene. Keep my exact face, facial features, and hair from my uploaded photos — do not restyle my hair, invent a different hair color, or change my body type. Match my facial likeness sharply. Standing centered in a brushed-metal elevator doorway, arms stretched out to both sides with palms flat against the elevator side panels, wide confident stance, looking straight at the camera with a fierce editorial expression. Wearing a voluminous cropped shaggy brown-and-black faux-fur jacket worn open and draped over the shoulders, a short black patent leather mini skirt with horizontal tiers and decorative front buckles, elbow-length glossy black gloves, slim black rectangular sunglasses, a black leather shoulder bag with a wide grommeted strap under one arm, and chunky silver earrings. Harsh direct-flash night-out photography, high contrast on metal walls, sharp shadows, fashion-editorial energy, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best — we keep your face and hair from the upload"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["street","elevator","fur","flash","editorial","y2k"]', 'noir', 'var(--pd-ink)',
  'Street · elevator · direct flash',
  'Arms out against brushed-metal elevator walls — shaggy fur jacket, patent mini, elbow gloves, slim shades, harsh flash.',
  NULL,
  '{"kicker":"Photoshoot · Elevator Fur Flash","howItWorks":["Upload clear photos of yourself","We recreate this exact scene, pose, and outfit on you","Pick a ratio and generate"]}',
  1, 0, 0, 0, 50, datetime('now')
),
(
  'street-bodega-snack-fisheye',
  'Bodega Snack Fisheye',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Put me from the reference photos into this exact scene. Keep my exact face, facial features, and hair from my uploaded photos — do not restyle my hair, invent a different hair color, or change my body type. Match my facial likeness sharply. Standing in the middle of a narrow convenience-store snack aisle packed with colorful chip bags and candy on wire shelves, one hand on hip, the other arm extended resting on a shelf edge, slight lean, confident street pose. Ultra-wide / fisheye digicam look with barrel distortion, harsh direct flash, grainy lo-fi film texture, bright recessed ceiling lights. Wearing a cropped dark acid-wash zip-up denim jacket with high collar and vertical ribbing, a very low-rise distressed olive-grey denim mini skirt with a circular metal logo patch on the hip, knee-high dark textured boots, and small dark wraparound sunglasses. Authentic bodega snapshot energy, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best — we keep your face and hair from the upload"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["street","bodega","fisheye","digicam","snack","y2k"]', 'amber', 'var(--pd-amber)',
  'Street · bodega aisle · digicam',
  'Ultra-wide digicam flash in a packed snack aisle — acid-wash crop jacket, low-rise mini, knee boots.',
  NULL,
  '{"kicker":"Photoshoot · Bodega Snack Fisheye","howItWorks":["Upload clear photos of yourself","We recreate this exact scene, pose, and outfit on you","Pick a ratio and generate"]}',
  1, 0, 0, 0, 51, datetime('now')
),
(
  'street-bodega-cooler-pose',
  'Bodega Cooler Pose',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Put me from the reference photos into this exact scene. Keep my exact face, facial features, and hair from my uploaded photos — do not restyle my hair, invent a different hair color, or change my body type. Match my facial likeness sharply. Full-body pose inside a bodega convenience store drink aisle next to glass-front refrigerated coolers stocked with colorful cans, snack shelves on the other side, fluorescent green-yellow cast, grainy lo-fi film look. Standing casually with one hand reaching up resting on the top metal frame of the cooler door, head tilted slightly toward camera, relaxed expression, weight on one hip. Wearing a white front-tie crop top, oversized dark-wash blue jeans with heavy horizontal rips and shredded panels worn low on the hips, a white long-sleeve sweatshirt with a light-blue graphic print tied around the waist, and chunky black sneakers. Eye-level vertical composition, soft focus background, no text overlays. Do not add tattoos that are not in my reference photos.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best — we keep your face and hair from the upload"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["street","bodega","cooler","film","ripped-jeans"]', 'mint', 'var(--pd-mint)',
  'Street · fridge aisle · film grain',
  'Hand on the cooler frame in a bodega drink aisle — white front-tie crop, oversized ripped jeans, sweater at the hips.',
  NULL,
  '{"kicker":"Photoshoot · Bodega Cooler Pose","howItWorks":["Upload clear photos of yourself","We recreate this exact scene, pose, and outfit on you","Pick a ratio and generate"]}',
  1, 0, 0, 0, 52, datetime('now')
),
(
  'street-stone-leather-editorial',
  'Stone Portico Editorial',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Put me from the reference photos into this exact scene. Keep my exact face, facial features, and hair from my uploaded photos — do not restyle my hair, invent a different hair color, or change my body type. Match my facial likeness sharply. Full-body editorial outdoor shot beside a grand classical stone building with ornate moldings and an ornate dark metal door. Leaning lower back against a low stone ledge, one arm extended with hand flat on the ledge, the other hand at the hip holding a small structured burgundy clutch, looking at the camera with a poised high-fashion expression, slightly low camera angle. Wearing a fitted black mock-neck turtleneck, an oversized black leather blazer draped open over the shoulders, black leather high-waisted shorts with a black belt and gold buckle, opaque deep burgundy tights, matching pointed burgundy high-heel pumps, slim dark-red tinted rectangular sunglasses, sleek burgundy leather gloves, and small chunky gold hoop earrings. Soft warm natural daylight, polished stone texture, monochrome-with-burgundy editorial look, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best — we keep your face and hair from the upload"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["street","editorial","leather","burgundy","classical"]', 'dusk', 'var(--pd-lilac)',
  'Street · classical facade · leather',
  'Leaning on a classical stone ledge — black turtleneck, leather blazer on shoulders, leather shorts, burgundy tights and heels.',
  NULL,
  '{"kicker":"Photoshoot · Stone Portico Editorial","howItWorks":["Upload clear photos of yourself","We recreate this exact scene, pose, and outfit on you","Pick a ratio and generate"]}',
  1, 0, 0, 0, 53, datetime('now')
),
(
  'studio-overhead-denim-digicam',
  'Overhead Denim Digicam',
  'shoot', 'image', 'Lifestyle', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Put me from the reference photos into this exact scene. Keep my exact face, facial features, and hair from my uploaded photos — do not restyle my hair, invent a different hair color, or change my body type. Match my facial likeness sharply. Extreme high-angle bird''s-eye editorial photo looking straight down, wide-angle lens with slight fisheye distortion so the head and shoulders feel larger. Leaning deep forward toward the camera looking up into the lens, torso almost parallel to the floor, one hand holding a small black point-and-shoot digital camera aimed at the viewer with a wrist strap, the other hand resting on a knee for balance. Wearing a light-wash denim halter top and matching frayed denim shorts, white ankle socks with beige pointed-toe slingback heels with a silver buckle on the toe, and large thick black-frame glasses with lightly rose-tinted lenses. Minimalist seamless off-white studio floor and backdrop, bright even editorial lighting, cool shadow tint, playful Y2K digicam fashion energy, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best — we keep your face and hair from the upload"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["lifestyle","studio","overhead","denim","digicam","y2k"]', 'ice', 'var(--pd-teal)',
  'Lifestyle · bird''s-eye · digicam',
  'Extreme high-angle wide shot leaning toward camera — denim halter + shorts, white socks, buckled heels, holding a digicam.',
  NULL,
  '{"kicker":"Photoshoot · Overhead Denim Digicam","howItWorks":["Upload clear photos of yourself","We recreate this exact scene, pose, and outfit on you","Pick a ratio and generate"]}',
  1, 0, 0, 0, 54, datetime('now')
),
(
  'street-times-square-lowbag',
  'Times Square Low Bag',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Put me from the reference photos into this exact scene. Keep my exact face, facial features, and hair from my uploaded photos — do not restyle my hair, invent a different hair color, or change my body type. Match my facial likeness sharply. Extreme low-angle ultra-wide / fisheye shot looking straight up from the crosswalk, mid-stride through Times Square NYC, skyscrapers and digital billboards curving inward from the lens distortion, bright daylight, white striped crosswalk. Looking down toward the camera with a confident expression, wearing slim dark rectangular sunglasses, holding a large glossy pale-pink designer tote bag very close to the lens so the bag dominates the foreground. Wearing a light-blue ribbed long-sleeve cropped sweater with matching light-blue mini shorts, reflective metallic silver platform boots with thick block heels and a chunky silver chain at the ankle, and a chunky silver chain necklace. High-energy NYC street editorial, sharp facial likeness, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best — we keep your face and hair from the upload"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["street","nyc","times-square","fisheye","bag","silver-boots"]', 'lilac', 'var(--pd-lilac)',
  'Street · Times Square · ultra-wide',
  'Extreme low fisheye looking up mid-stride in a crosswalk — baby-blue set, silver platform boots, glossy pink tote filling the frame.',
  NULL,
  '{"kicker":"Photoshoot · Times Square Low Bag","howItWorks":["Upload clear photos of yourself","We recreate this exact scene, pose, and outfit on you","Pick a ratio and generate"]}',
  1, 0, 0, 0, 55, datetime('now')
),
(
  'street-clocktower-butterfly-heels',
  'Clocktower Butterfly Heels',
  'shoot', 'image', 'Street', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Put me from the reference photos into this exact scene. Keep my exact face, facial features, and hair from my uploaded photos — do not restyle my hair, invent a different hair color, or change my body type. Match my facial likeness sharply. Dramatic full-body extreme low-angle shot looking up from the ground, wide stance bent forward at the waist, one arm reaching down toward the camera holding sunglasses, the other arm extended high behind holding a small crescent beaded purse by a thin strap, one leg forward for depth. Standing on flat concrete with a large multi-story red brick building and central clock tower behind under a deep blue sky with fluffy white clouds. Wearing a long-sleeve chocolate-brown open-back crop top with thin wrap ties at the waist, very short dark-blue denim cutoff shorts, bright yellow satin platform sandals with chunky heels and long yellow wrap cords climbing up the legs to mid-thigh covered in colorful 3D butterfly appliqués in pink, blue, and yellow, large gold hoop earrings, and chunky colorful rings. Bright direct daylight, high-contrast saturated Y2K fashion energy, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body shots work best — we keep your face and hair from the upload"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["street","y2k","butterfly","platforms","clocktower","low-angle"]', 'pink', 'var(--pd-pink)',
  'Street · low angle · Y2K platforms',
  'Dramatic low-angle wide stance under a brick clock tower — brown wrap crop, denim cutoffs, yellow wrap platforms with butterfly charms.',
  NULL,
  '{"kicker":"Photoshoot · Clocktower Butterfly Heels","howItWorks":["Upload clear photos of yourself","We recreate this exact scene, pose, and outfit on you","Pick a ratio and generate"]}',
  1, 0, 0, 0, 56, datetime('now')
)
ON CONFLICT(id) DO UPDATE SET
  title=excluded.title,
  kind=excluded.kind,
  type=excluded.type,
  category=excluded.category,
  provider=excluded.provider,
  model=excluded.model,
  input_json=excluded.input_json,
  fields_json=excluded.fields_json,
  credit_cost=excluded.credit_cost,
  quality_json=excluded.quality_json,
  aspects_json=excluded.aspects_json,
  quantities_json=excluded.quantities_json,
  eta=excluded.eta,
  tags_json=excluded.tags_json,
  tone=excluded.tone,
  accent=excluded.accent,
  subtitle=excluded.subtitle,
  description=excluded.description,
  preview_image=COALESCE(templates.preview_image, excluded.preview_image),
  meta=excluded.meta,
  is_featured=excluded.is_featured,
  is_hidden=excluded.is_hidden,
  is_admin_only=excluded.is_admin_only,
  is_adult=excluded.is_adult,
  sort_order=excluded.sort_order,
  updated_at=excluded.updated_at;

