-- Ten location Selfie photoshoot presets for /shoots.
-- User-requested: Bali motorcycle, Santa Teresa surf sunset, Hawaii GoPro surf,
-- Range Rover latte drive. Plus six more travel locations.
-- Idempotent upserts.

INSERT INTO templates (
  id, title, kind, type, category, provider, model,
  input_json, fields_json, credit_cost, quality_json, aspects_json, quantities_json,
  eta, tags_json, tone, accent, subtitle, description, preview_image, meta,
  is_featured, is_hidden, is_admin_only, is_adult, sort_order, updated_at
) VALUES
(
  'bali-motorcycle-selfie',
  'Bali Motorcycle Selfie',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me on a motorcycle scooter in Bali. Ultra-wide front-camera selfie, arm extended holding the phone, sitting on a classic scooter on a tropical Balinese road, lush green rice terraces or palm-lined street behind, warm golden daylight, wind in hair, candid vacation energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays, no helmet blocking the face.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face photos work best for the scooter selfie angle"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["bali","motorcycle","scooter","selfie","travel",".5"]', 'amber', 'var(--pd-amber)',
  'Selfie · Bali · scooter',
  'Bali scooter selfie — tropical road, palms or rice terraces, wind-in-hair .5 flash.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160376485.png'"kicker":"Photoshoot · Travel Selfie","howItWorks":["Upload clear photos of yourself","We put you on a Bali motorcycle scooter selfie","Pick a ratio and generate"]}',
  1, 0, 0, 0, 20, datetime('now')
),
(
  'santa-teresa-surf-sunset',
  'Santa Teresa Surf Sunset',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me surfing in Santa Teresa, Costa Rica at sunset. Ultra-wide front-camera selfie, sitting out on my surfboard in the ocean waiting for a wave, wearing a sleek black wetsuit, wet hair slicked and dripping, warm golden-pink sunset sky reflecting on the water, distant tropical shoreline, calm ocean swell, candid surf lifestyle energy, sharp facial likeness to the reference photos, natural skin texture with water droplets, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face photos — wetsuit and board are generated for the scene"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["costarica","santateresa","surf","wetsuit","sunset","selfie"]', 'dusk', 'var(--pd-pink)',
  'Selfie · Costa Rica · sunset board',
  'Santa Teresa sunset surf selfie — black wetsuit, wet hair, sitting on the board.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160322616.png'"kicker":"Photoshoot · Surf Selfie","howItWorks":["Upload clear photos of yourself","We place you on a Santa Teresa sunset surfboard selfie","Generate the still"]}',
  1, 0, 0, 0, 21, datetime('now')
),
(
  'hawaii-surf-gopro',
  'Hawaii Surf GoPro',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe GoPro-style selfie of me surfing in Hawaii. Lying on my stomach on a surfboard looking straight into a wide GoPro camera mounted low on the nose of the board, wearing a sleek black wetsuit, wet hair slicked and dripping, bright tropical Hawaiian ocean water and soft blue sky, board tip visible in the foreground, candid surf energy, sharp facial likeness to the reference photos, natural skin texture with water droplets, ultra-wide fisheye GoPro distortion, authentic action-cam snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face-forward photos look best for the GoPro board angle"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["hawaii","surf","gopro","wetsuit","selfie","ocean"]', 'teal', 'var(--pd-teal)',
  'Selfie · Hawaii · GoPro board',
  'Hawaii surf GoPro selfie — lying on the board, black wetsuit, wet hair, fisheye angle.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160299156.png'"kicker":"Photoshoot · Surf Selfie","howItWorks":["Upload clear photos of yourself","We put you on a Hawaii surfboard GoPro selfie","Generate the still"]}',
  1, 0, 0, 0, 22, datetime('now')
),
(
  'rangerover-latte-selfie',
  'Range Rover Latte Selfie',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me driving a luxury Range Rover. Ultra-wide front-camera selfie from the driver seat, arm extended, holding a latte coffee mug in the other hand near the lens, wearing a pastel pink cami top and matching pink leggings, glowing nice tan, long hair down and flowing, delicate gold necklace, gold watch on wrist, french manicure nails, diamond ring visible on the hand holding the mug, soft daylight through the windshield, premium leather interior, candid rich-girl commute energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + hand/upper-body photos help nail jewelry and manicure details"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["rangerover","latte","selfie","pink","luxury","drive"]', 'pink', 'var(--pd-pink)',
  'Selfie · Range Rover · latte',
  'Range Rover driver selfie — pastel pink fit, latte in hand, gold jewelry, french manicure.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160410742.png'"kicker":"Photoshoot · Drive Selfie","howItWorks":["Upload clear photos of yourself","We drop you into a Range Rover latte selfie in the pink fit","Generate the still"]}',
  1, 0, 0, 0, 23, datetime('now')
),
(
  'paris-cafe-terrace-selfie',
  'Paris Café Terrace',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me at a Paris café terrace. Ultra-wide front-camera selfie, arm extended, sitting at a classic sidewalk café table with a tiny espresso cup, Haussmann buildings and wrought-iron balconies softly blurred behind, soft Parisian afternoon light mixed with digital flash, chic casual outfit, candid European vacation energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face photos work great for café terrace framing"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["paris","cafe","terrace","selfie","travel",".5"]', 'mint', 'var(--pd-mint)',
  'Selfie · Paris · café terrace',
  'Paris sidewalk café selfie — espresso, Haussmann backdrop, soft .5 flash.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160272881.png'"kicker":"Photoshoot · Travel Selfie","howItWorks":["Upload clear photos of yourself","We place you on a Paris café terrace selfie","Generate the still"]}',
  1, 0, 0, 0, 24, datetime('now')
),
(
  'tokyo-neon-night-selfie',
  'Tokyo Neon Night',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me in Tokyo at night. Ultra-wide front-camera selfie, arm extended, standing on a busy Shinjuku or Shibuya sidewalk, neon signs and Japanese storefronts glowing behind, rainy asphalt reflections optional, digital flash popping on my face against the neon city, candid cool night-out energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face photos look best with neon night flash"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["tokyo","neon","night","selfie","japan",".5"]', 'lilac', 'var(--pd-lilac)',
  'Selfie · Tokyo · neon night',
  'Tokyo night selfie — neon signs, flash on face, crowded sidewalk energy.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160568004.png'"kicker":"Photoshoot · Travel Selfie","howItWorks":["Upload clear photos of yourself","We drop you into a Tokyo neon-night selfie","Generate the still"]}',
  1, 0, 0, 0, 25, datetime('now')
),
(
  'amalfi-cliff-selfie',
  'Amalfi Cliff Selfie',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me on the Amalfi Coast. Ultra-wide front-camera selfie, arm extended, standing on a cliffside terrace or winding coastal overlook, pastel Italian cliffside towns stacked below, bright Mediterranean sea and sky, warm afternoon sun mixed with digital flash, breezy vacation hair, candid Italian summer energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body photos work best for cliff overlook framing"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["amalfi","italy","cliff","selfie","travel",".5"]', 'teal', 'var(--pd-teal)',
  'Selfie · Amalfi · cliffside',
  'Amalfi Coast cliff selfie — pastel towns below, Mediterranean blue, sunny .5 flash.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160731220.png'"kicker":"Photoshoot · Travel Selfie","howItWorks":["Upload clear photos of yourself","We put you on an Amalfi cliffside selfie","Generate the still"]}',
  1, 0, 0, 0, 26, datetime('now')
),
(
  'london-black-cab-selfie',
  'London Black Cab',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me in the back of a classic London black cab. Ultra-wide front-camera selfie, arm extended, sitting on the rear bench seat, rainy London street and red double-decker bus softly visible through the window behind, cool overcast daylight mixed with digital flash inside the cab, candid city travel energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face photos work best for the cab interior selfie"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["london","blackcab","selfie","uk","travel",".5"]', 'noir', 'var(--pd-lilac)',
  'Selfie · London · black cab',
  'London black-cab selfie — rear seat, rainy street through the window, cool .5 flash.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160555210.png'"kicker":"Photoshoot · Travel Selfie","howItWorks":["Upload clear photos of yourself","We seat you in a London black-cab selfie","Generate the still"]}',
  1, 0, 0, 0, 27, datetime('now')
),
(
  'santorini-caldera-selfie',
  'Santorini Caldera',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me in Santorini. Ultra-wide front-camera selfie, arm extended, standing on a whitewashed caldera terrace with blue-domed churches and the Aegean sea behind, bright Greek island sun mixed with digital flash, wind-tousled hair, candid vacation energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face photos look great against the white-and-blue backdrop"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["santorini","greece","caldera","selfie","travel",".5"]', 'ice', 'var(--pd-mint)',
  'Selfie · Santorini · caldera',
  'Santorini caldera selfie — white terrace, blue dome, Aegean backdrop, sunny .5 flash.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160464935.png'"kicker":"Photoshoot · Travel Selfie","howItWorks":["Upload clear photos of yourself","We place you on a Santorini caldera terrace selfie","Generate the still"]}',
  1, 0, 0, 0, 28, datetime('now')
),
(
  'lake-como-boat-selfie',
  'Lake Como Boat',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me on a wooden boat on Lake Como. Ultra-wide front-camera selfie, arm extended, sitting toward the bow of a classic Riva-style boat, turquoise alpine lake water and villa-dotted mountains behind, soft golden late-afternoon light mixed with digital flash, breezy chic vacation energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"low","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body photos work best for the boat angle"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["lakecomo","italy","boat","selfie","travel",".5"]', 'teal', 'var(--pd-teal)',
  'Selfie · Lake Como · boat',
  'Lake Como boat selfie — classic wooden boat, alpine lake, villa mountains, golden light.',
  NULL'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785160542426.png'"kicker":"Photoshoot · Travel Selfie","howItWorks":["Upload clear photos of yourself","We put you on a Lake Como boat selfie","Generate the still"]}',
  1, 0, 0, 0, 29, datetime('now')
)
ON CONFLICT(id) DO UPDATE SET
  title=excluded.title,
  kind=excluded.kind,
  type=excluded.type,
  category=excluded.category,
  provider=excluded.provider,
  model=excluded.model,
  input_json=excluded.input_json,
  fields_json=excluded.fields_json,
  credit_cost=excluded.credit_cost,
  quality_json=excluded.quality_json,
  aspects_json=excluded.aspects_json,
  quantities_json=excluded.quantities_json,
  eta=excluded.eta,
  tags_json=excluded.tags_json,
  tone=excluded.tone,
  accent=excluded.accent,
  subtitle=excluded.subtitle,
  description=excluded.description,
  preview_image=COALESCE(excluded.preview_image, templates.preview_image),
  meta=excluded.meta,
  is_featured=excluded.is_featured,
  is_hidden=excluded.is_hidden,
  is_admin_only=excluded.is_admin_only,
  is_adult=excluded.is_adult,
  sort_order=excluded.sort_order,
  updated_at=excluded.updated_at;
