-- Five beauty / tropical Selfie photoshoot presets for /shoots.
-- Idempotent upserts.

INSERT INTO templates (
  id, title, kind, type, category, provider, model,
  input_json, fields_json, credit_cost, quality_json, aspects_json, quantities_json,
  eta, tags_json, tone, accent, subtitle, description, preview_image, meta,
  is_featured, is_hidden, is_admin_only, is_adult, sort_order, updated_at
) VALUES
(
  'grwm-lipgloss-selfie',
  'GRWM Lip Gloss',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me getting ready — mid GRWM moment applying lip gloss. Ultra-wide front-camera selfie, arm extended, holding a clear lip-gloss tube or wand near my lips, just dabbing on shine, vanity mirror and soft bathroom or bedroom lights behind, digital flash mixed with warm vanity bulbs, candid get-ready energy, sharp facial likeness to the reference photos, natural skin texture, glossy lips catching the flash, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear close-up face photos work best for GRWM lip-gloss framing"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["grwm","selfie","lipgloss","beauty","flash",".5"]', 'pink', 'var(--pd-pink)',
  'Selfie · GRWM · lip gloss',
  'Get-ready selfie mid lip-gloss — vanity lights, gloss wand in frame, cool .5 flash.',
  'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785126638092.png',
  '{"kicker":"Photoshoot · GRWM Selfie","howItWorks":["Upload clear photos of yourself","We put you in a GRWM lip-gloss selfie","Pick a ratio and generate"]}',
  1, 0, 0, 0, 1, datetime('now')
),
(
  'grwm-face-cream-selfie',
  'GRWM Face Cream',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me getting ready — mid GRWM skincare moment applying face cream with completely bare skin, no makeup. Ultra-wide front-camera selfie, arm extended, fingertips gently pressing moisturizer into cheeks, clean dewy skin with no foundation lipstick or mascara, bathroom vanity and soft morning light behind, digital flash mixed with window light, fresh clean-girl energy, sharp facial likeness to the reference photos, natural skin texture and pores visible, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Natural face photos (little or no makeup) look best"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["grwm","selfie","skincare","cream","bareface",".5"]', 'mint', 'var(--pd-mint)',
  'Selfie · GRWM · bare skin cream',
  'Bare-face GRWM selfie rubbing in face cream — dewy skin, vanity light, soft .5 flash.',
  'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785126706679.png',
  '{"kicker":"Photoshoot · GRWM Selfie","howItWorks":["Upload clear photos of yourself","We place you in a bare-face face-cream GRWM selfie","Generate the skincare still"]}',
  1, 0, 0, 0, 2, datetime('now')
),
(
  'facial-bed-selfie',
  'Facial Bed Selfie',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me laying down on a spa facial bed mid-facial treatment. Ultra-wide front-camera selfie from a low reclined angle, arm holding the phone above my face, towel wrapped in hair or headband, soft cream or serum on skin, spa treatment room ceiling and warm soft lights above, optional esthetician hands gently applying product at the edge of frame, calm spa energy, sharp facial likeness to the reference photos, natural skin texture, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face-forward photos work best for the reclined selfie angle"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["facial","selfie","spa","skincare","layover",".5"]', 'lilac', 'var(--pd-lilac)',
  'Selfie · spa facial · laying down',
  'Reclined spa facial selfie — towel in hair, soft cream, treatment-bed angle, .5 phone flash.',
  'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785126814462.png',
  '{"kicker":"Photoshoot · Spa Selfie","howItWorks":["Upload clear photos of yourself","We put you on a facial bed mid-treatment selfie","Pick a ratio and generate"]}',
  1, 0, 0, 0, 3, datetime('now')
),
(
  'ocean-underwater-selfie',
  'Ocean Underwater Selfie',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone underwater selfie of me in clear tropical ocean water. Ultra-wide front-camera selfie underwater, arm extended holding the waterproof phone, bright blue crystal-clear water, small colorful tropical fish swimming below and around me, sunlight shafts from the surface above, wet hair floating, wearing a cute modest swimsuit, happy tropical vacation energy, sharp facial likeness to the reference photos, natural skin texture, bubbles optional, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face photos help — swimsuit will be generated for the scene"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["ocean","underwater","selfie","tropical","fish",".5"]', 'teal', 'var(--pd-teal)',
  'Selfie · underwater · tropical fish',
  'Clear blue ocean underwater selfie — fish swimming below, wet hair, cute swimsuit, tropical light.',
  'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785126861577.png',
  '{"kicker":"Photoshoot · Tropical Selfie","howItWorks":["Upload clear photos of yourself","We drop you into a clear tropical ocean selfie with fish below","Generate the underwater still"]}',
  1, 0, 0, 0, 4, datetime('now')
),
(
  'tropical-wet-hair-selfie',
  'Tropical Wet Hair Selfie',
  'shoot', 'image', 'Selfie', 'replicate', 'openai/gpt-image-2',
  '{"prompt":"Generate a cool-vibe .5 iPhone selfie of me in tropical ocean water at the surface — wet hair, cute swimsuit, vacation vibes. Ultra-wide front-camera selfie, arm extended, standing or floating chest-deep in bright turquoise water, wet hair slicked and dripping, soft tropical sun, distant palm shoreline or clear horizon behind, digital flash mixed with harsh midday sun, candid cute beach energy, sharp facial likeness to the reference photos, natural skin texture with water droplets, slightly distorted .5 lens look, authentic phone snapshot, no text overlays.","quality":"auto","background":"auto","moderation":"auto","aspect_ratio":"{{aspect}}","input_images":"{{files*}}","output_format":"webp","number_of_images":1,"output_compression":90}',
  '[{"key":"files","type":"file","label":"Your photos","required":true,"multiple":true,"max":4,"accept":"image/*","help":"Clear face + upper-body photos work great for wet-hair beach framing"}]',
  5, NULL, '["match","1:1","2:3","3:2"]', '[1,2,4]',
  '~2 min', '["tropical","beach","selfie","wethair","swimsuit",".5"]', 'amber', 'var(--pd-amber)',
  'Selfie · wet hair · turquoise water',
  'Tropical surface-water selfie — wet hair, cute swimsuit, turquoise sea, sunny .5 flash.',
  'https://pixiecdn.b-cdn.net/gen_d80b0323-9f76-44ee-bb08-a6aed948e196_1785126982620.png',
  '{"kicker":"Photoshoot · Tropical Selfie","howItWorks":["Upload clear photos of yourself","We put you in a wet-hair tropical ocean selfie","Pick a ratio and generate"]}',
  1, 0, 0, 0, 5, datetime('now')
)
ON CONFLICT(id) DO UPDATE SET
  title=excluded.title,
  kind=excluded.kind,
  type=excluded.type,
  category=excluded.category,
  provider=excluded.provider,
  model=excluded.model,
  input_json=excluded.input_json,
  fields_json=excluded.fields_json,
  credit_cost=excluded.credit_cost,
  quality_json=excluded.quality_json,
  aspects_json=excluded.aspects_json,
  quantities_json=excluded.quantities_json,
  eta=excluded.eta,
  tags_json=excluded.tags_json,
  tone=excluded.tone,
  accent=excluded.accent,
  subtitle=excluded.subtitle,
  description=excluded.description,
  preview_image=COALESCE(excluded.preview_image, templates.preview_image),
  meta=excluded.meta,
  is_featured=excluded.is_featured,
  is_hidden=excluded.is_hidden,
  is_admin_only=excluded.is_admin_only,
  is_adult=excluded.is_adult,
  sort_order=excluded.sort_order,
  updated_at=excluded.updated_at;
